"use client";
import { useState } from 'react';
import { Bell, Building2, CalendarClock, Download, FileText, Home, Loader2, Receipt, Wrench } from 'lucide-react';
import ProtectedRoute from '../components/ProtectedRoute';
import useTenantPortal from '../hooks/useTenantPortal';
import { createTenantMaintenance, downloadTenantDocument } from '../services/tenantPortalService';

const money = (value = 0) => `${Number(value || 0).toLocaleString('fr-FR')} FCFA`;
const date = (value) => value ? new Date(value).toLocaleDateString('fr-FR') : '—';
const tabs = ['Tableau de bord', 'Baux', 'Paiements', 'Documents', 'Préavis', 'Maintenance', 'Profil'];
const Card = ({ icon: Icon, label, value, detail }) => <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3 text-slate-500"><span className="rounded-xl bg-blue-50 p-2 text-blue-700"><Icon size={19}/></span><span className="text-sm">{label}</span></div><p className="mt-3 text-xl font-bold text-slate-900">{value ?? '—'}</p>{detail && <p className="mt-1 text-xs text-slate-500">{detail}</p>}</div>;

function Content() {
  const portal = useTenantPortal(); const [tab, setTab] = useState(tabs[0]); const [form, setForm] = useState({ category: 'plomberie', description: '', photos: [] }); const [saving, setSaving] = useState(false);
  if (portal.loading) return <div className="min-h-[60vh] grid place-items-center"><Loader2 className="animate-spin text-blue-700" size={36}/></div>;
  if (portal.error) return <div className="mx-auto my-20 max-w-xl rounded-2xl border border-amber-200 bg-amber-50 p-6 text-amber-900"><h1 className="text-xl font-bold">Espace locataire indisponible</h1><p className="mt-2">{portal.error}</p><p className="mt-3 text-sm">Votre compte doit d’abord être rattaché à un dossier locataire validé.</p></div>;
  const d = portal.dashboard || {};
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { await createTenantMaintenance(form); setForm({ category: 'plomberie', description: '', photos: [] }); await portal.reload(); } finally { setSaving(false); } };
  return <main className="min-h-screen bg-slate-50 pb-16">
    <header className="bg-gradient-to-r from-slate-950 to-blue-950 text-white"><div className="mx-auto max-w-7xl px-5 py-10"><p className="text-sm text-blue-200">Portail sécurisé</p><h1 className="mt-1 text-3xl font-bold">Bonjour {portal.profile?.prenom || ''}</h1><p className="mt-2 text-slate-300">Bail, paiements, documents et demandes réunis au même endroit.</p></div></header>
    <div className="mx-auto max-w-7xl px-5"><nav className="-mt-4 flex gap-1 overflow-x-auto rounded-2xl bg-white p-2 shadow-lg" aria-label="Sections du portail">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm font-medium ${tab === item ? 'bg-blue-700 text-white' : 'text-slate-600 hover:bg-slate-100'}`}>{item}</button>)}</nav>
    <section className="mt-7">
      {tab === 'Tableau de bord' && <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card icon={CalendarClock} label="Prochain paiement" value={d.prochainPaiement ? money(d.prochainPaiement.restant) : 'À jour'} detail={d.prochainPaiement ? `${d.prochainPaiement.mois}/${d.prochainPaiement.annee}` : undefined}/><Card icon={Receipt} label="Montant restant" value={money(d.montantRestant)}/><Card icon={Home} label="Bail actif" value={d.bailActif?.statut || 'Aucun'} detail={`${date(d.bailActif?.dateEntree)} → ${date(d.bailActif?.dateFinBail)}`}/><Card icon={CalendarClock} label="Durée restante" value={d.dureeRestanteJours == null ? '—' : `${d.dureeRestanteJours} jours`}/><Card icon={Building2} label="Prochain renouvellement" value={date(d.prochainRenouvellement)}/><Card icon={FileText} label="Préavis actif" value={d.preavisActif ? d.preavisActif.statut : 'Non'}/><Card icon={Wrench} label="Maintenance ouverte" value={d.maintenanceOuverte || 0}/><Card icon={Bell} label="Notifications" value={d.notifications?.filter((n) => !n.read).length || 0} detail="non lues"/></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><Panel title="Documents récents">{d.documentsRecents?.map((doc) => <Row key={doc._id} main={doc.nom} sub={date(doc.dateGeneration)}/>)}</Panel><Panel title="Notifications">{d.notifications?.map((n) => <Row key={n._id} main={n.title} sub={n.body}/>)}</Panel></div></>}
      {tab === 'Baux' && <Panel title="Historique des baux">{portal.leases.map((lease) => <Row key={lease._id} main={`${lease.bien?.title || lease.adresseBien || 'Bien loué'} · ${lease.statut}`} sub={`${date(lease.dateEntree)} → ${date(lease.dateFinBail)} · ${money(lease.montantLoyer)}`}/>)}</Panel>}
      {tab === 'Paiements' && <><div className="grid gap-4 sm:grid-cols-3 mb-5"><Card icon={Receipt} label="Total dû" value={money(portal.payments.summary?.du)}/><Card icon={Receipt} label="Total reçu" value={money(portal.payments.summary?.recu)}/><Card icon={CalendarClock} label="Pénalités" value={money(portal.payments.summary?.penalites)}/></div><Panel title="Échéancier et paiements">{portal.payments.payments.map((p) => <Row key={p._id} main={`${p.mois}/${p.annee} · ${p.statut}`} sub={`${money(p.montantTotal ?? p.montant)} · reçu ${money(p.montantRecu)} · restant ${money(p.restant)}${p.reference ? ` · réf. ${p.reference}` : ''}`}/>)}</Panel></>}
      {tab === 'Documents' && <Panel title="Mes documents">{portal.documents.documents.map((doc) => <div key={doc._id} className="flex items-center justify-between border-b border-slate-100 py-4"><div><p className="font-medium">{doc.nom}</p><p className="text-xs text-slate-500">{doc.type} · {date(doc.dateGeneration)}</p></div><button onClick={() => downloadTenantDocument(doc._id, doc.nom)} className="rounded-lg border p-2 text-blue-700" aria-label={`Télécharger ${doc.nom}`}><Download size={18}/></button></div>)}</Panel>}
      {tab === 'Préavis' && <Panel title="Mon préavis">{portal.notice ? <div className="grid gap-4 sm:grid-cols-2"><Card icon={FileText} label="Date de dépôt" value={date(portal.notice.dateDepot)}/><Card icon={CalendarClock} label="Départ prévu" value={date(portal.notice.dateDepartPrevue)}/><Card icon={CalendarClock} label="Jours restants" value={`${portal.notice.joursRestants} jours`}/><Card icon={FileText} label="Statut" value={portal.notice.statut} detail={portal.notice.verrouille ? 'Préavis validé, non modifiable' : undefined}/></div> : <p className="text-slate-500">Aucun préavis actif.</p>}</Panel>}
      {tab === 'Maintenance' && <div className="grid gap-6 lg:grid-cols-2"><Panel title="Créer une demande"><form onSubmit={submit} className="space-y-4"><select value={form.category} onChange={(e) => setForm({...form, category:e.target.value})} className="w-full rounded-xl border p-3">{['plomberie','electricite','structure','equipement','nuisible','serrurerie','peinture','autre'].map((v)=><option key={v}>{v}</option>)}</select><textarea required minLength={5} value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})} placeholder="Décrivez précisément le problème" className="min-h-32 w-full rounded-xl border p-3"/><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(e)=>setForm({...form,photos:[...e.target.files].slice(0,5)})}/><button disabled={saving} className="rounded-xl bg-blue-700 px-5 py-3 font-semibold text-white disabled:opacity-50">{saving ? 'Envoi…' : 'Envoyer la demande'}</button></form></Panel><Panel title="Suivi des interventions">{portal.maintenance.tickets.map((t)=><Row key={t._id} main={`${t.category} · ${t.status}`} sub={`${t.description} · créée le ${date(t.createdAt)}${t.scheduledFor ? ` · prévue le ${date(t.scheduledFor)}` : ''}`}/>)}</Panel></div>}
      {tab === 'Profil' && <Panel title="Mon profil"><dl className="grid gap-4 sm:grid-cols-2">{[['Nom',`${portal.profile.prenom || ''} ${portal.profile.nom || ''}`],['Email',portal.profile.email],['Téléphone',portal.profile.telephone],['Adresse',portal.profile.adresse],['Ville',portal.profile.ville],['Profession',portal.profile.profession]].map(([k,v])=><div key={k}><dt className="text-xs uppercase text-slate-400">{k}</dt><dd className="mt-1 font-medium">{v || '—'}</dd></div>)}</dl></Panel>}
    </section></div>
  </main>;
}
const Panel = ({ title, children }) => <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-3 text-lg font-bold text-slate-900">{title}</h2>{children || <p className="text-sm text-slate-500">Aucune donnée.</p>}</div>;
const Row = ({ main, sub }) => <div className="border-b border-slate-100 py-3 last:border-0"><p className="font-medium text-slate-800">{main}</p><p className="mt-1 text-sm text-slate-500">{sub}</p></div>;
export default function TenantPortalPage() { return <ProtectedRoute><Content/></ProtectedRoute>; }
