'use client';
import { useCallback, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { RefreshCw, Search, Users, AlertTriangle, LayoutDashboard, Columns3, CalendarDays, ScanSearch, GitMerge, Gauge, Cog } from 'lucide-react';
import { getCrmCustomers, synchronizeCrmCustomers } from '../../services/crmService';
import { resolveWebDestination } from '../../navigation/navigationSdk';
import CrmDashboardPanel from '../../components/crm/CrmDashboardPanel';
import CrmPipelineBoard from '../../components/crm/CrmPipelineBoard';
import CrmGlobalSearch from '../../components/crm/CrmGlobalSearch';
import CrmDuplicatesCenter from '../../components/crm/CrmDuplicatesCenter';
import CrmActivitiesAgenda from '../../components/crm/CrmActivitiesAgenda';
import CrmAutomationCockpit from '../../components/crm/CrmAutomationCockpit';
import CrmAutomationRulesPanel from '../../components/crm/CrmAutomationRulesPanel';

const STAGES = ['prospect','qualification','proposition','negociation','contrat','client_actif','fidelisation','ancien_client'];
const tabs=[['dashboard','CRM_CUSTOMERS',LayoutDashboard,'Cockpit'],['pipeline','CRM_PIPELINE',Columns3,'Pipeline'],['search','CRM_SEARCH',ScanSearch,'Recherche globale'],['duplicates','CRM_DUPLICATES',GitMerge,'Doublons'],['activities','CRM_ACTIVITIES',CalendarDays,'Activités'],['cockpit','CRM_COCKPIT',Gauge,'Cockpit commercial'],['automation','CRM_AUTOMATION_RULES',Cog,'Automatisations']];
export default function CrmCustomersPage(){
  const params=useSearchParams();const view=params.get('view')||'dashboard';const[result,setResult]=useState({customers:[],total:0});const[search,setSearch]=useState('');const[stage,setStage]=useState('');const[relation,setRelation]=useState('');const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[syncing,setSyncing]=useState(false);const[syncResult,setSyncResult]=useState(null);
  const load=useCallback(async()=>{setLoading(true);setError('');try{setResult(await getCrmCustomers({search,stage,relation,limit:100}));}catch(e){setError(e.response?.data?.message||'Chargement du CRM impossible.');}finally{setLoading(false);}},[search,stage,relation]);useEffect(()=>{load();},[load]);
  const sync=async()=>{setSyncing(true);setError('');try{const data=await synchronizeCrmCustomers();setSyncResult(data);await load();}catch(e){setError(e.response?.data?.message||'Consolidation impossible.');}finally{setSyncing(false);}};
  return <main className="space-y-6 p-3 sm:p-6"><header className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div><h1 className="text-2xl font-bold text-slate-900">CRM 360° — Poste de pilotage</h1><p className="text-sm text-slate-600">Customer, pipeline, agenda et consolidation dans un seul CRM transversal.</p></div><button onClick={sync} disabled={syncing} className="inline-flex items-center justify-center gap-2 rounded-lg bg-teal-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60"><RefreshCw size={16} className={syncing?'animate-spin':''}/>{syncing?'Consolidation…':'Consolider les sources'}</button></header>
  <nav aria-label="Sections CRM" className="flex gap-2 overflow-x-auto pb-1">{tabs.map(([id,destination,Icon,label])=><Link key={id} href={resolveWebDestination(destination)} className={`inline-flex shrink-0 items-center gap-2 rounded-full px-4 py-2 text-sm font-medium ${view===id?'bg-slate-900 text-white':'bg-white text-slate-700 shadow-sm ring-1 ring-slate-200'}`}><Icon size={16}/>{label}</Link>)}</nav>
  {syncResult&&<p className="rounded-lg border border-teal-200 bg-teal-50 p-3 text-sm text-teal-900">{syncResult.scanned} sources analysées · {syncResult.created} fiches créées · {syncResult.updated} enrichissements · {syncResult.conflicts?.length||0} ambiguïté(s).</p>}{error&&<p role="alert" className="flex gap-2 rounded-lg bg-red-50 p-3 text-red-800"><AlertTriangle size={18}/>{error}</p>}
  {view==='pipeline'&&<CrmPipelineBoard/>}{view==='search'&&<CrmGlobalSearch/>}{view==='duplicates'&&<CrmDuplicatesCenter/>}{view==='activities'&&<CrmActivitiesAgenda/>}{view==='cockpit'&&<CrmAutomationCockpit/>}{view==='automation'&&<CrmAutomationRulesPanel/>}
  {view==='dashboard'&&<><CrmDashboardPanel/><section className="space-y-4"><div className="flex items-center gap-2"><Users size={18}/><h2 className="text-lg font-semibold">Customers</h2><span className="text-sm text-slate-500">{result.total}</span></div><div className="grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-[1fr_200px_200px]"><label className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input aria-label="Rechercher un customer" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nom, entreprise, email, téléphone" className="w-full rounded-lg border py-2.5 pl-10 pr-3"/></label><select aria-label="Filtrer par étape" value={stage} onChange={e=>setStage(e.target.value)} className="rounded-lg border px-3"><option value="">Toutes les étapes</option>{STAGES.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select><select aria-label="Filtrer par profil métier" value={relation} onChange={e=>setRelation(e.target.value)} className="rounded-lg border px-3"><option value="">Tous les profils</option><option value="exploitant_etablissement">Exploitant d&apos;établissement</option><option value="proprietaire">Propriétaire immobilier</option><option value="locataire">Locataire</option><option value="prospect">Prospect</option></select></div>{loading?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1,2,3,4,5,6].map(x=><div key={x} className="h-44 animate-pulse rounded-xl bg-slate-100"/>)}</div>:result.customers.length===0?<div className="rounded-xl border border-dashed p-10 text-center text-slate-500">Aucune fiche. Lancez la consolidation des sources existantes.</div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{result.customers.map(c=><Link key={c._id} href={resolveWebDestination('CRM_CUSTOMER_DETAILS',{id:c._id})} className="rounded-xl border bg-white p-5 shadow-sm transition hover:border-teal-500"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{c.displayName}</h3><p className="text-sm text-slate-500">{c.company||c.kind}</p></div><span className={`rounded-full px-2 py-1 text-xs ${c.status==='merge_review'?'bg-amber-100 text-amber-800':'bg-teal-50 text-teal-700'}`}>{c.status}</span></div><p className="mt-3 text-sm">{c.emails?.[0]||'Email non renseigné'}</p><p className="text-sm">{c.phones?.[0]||'Téléphone non renseigné'}</p><div className="mt-4 flex flex-wrap gap-1">{c.relations?.map(r=><span key={r} className="rounded bg-slate-100 px-2 py-1 text-xs">{r.replaceAll('_',' ')}</span>)}</div><p className="mt-4 text-xs text-slate-500">{c.sourceRefs?.length||0} source(s) · {c.opportunities?.count||0} opportunité(s)</p></Link>)}</div>}</section></>}
  </main>;
}
