'use client';
import { useCallback, useEffect, useState } from 'react';
import { ArrowLeft, CalendarPlus, CircleDollarSign, FileText, MessageCircle, Plus } from 'lucide-react';
import Link from 'next/link';
import { createCrmActivity, createCrmOpportunity, getCrmCustomer, moveCrmOpportunity, updateCrmActivity } from '../../services/crmService';
import { resolveWebDestination } from '../../navigation/navigationSdk';

const STAGES=['prospect','qualification','proposition','negociation','contrat','client_actif','fidelisation','ancien_client'];
const money=(n)=>n===null?'Non disponible':new Intl.NumberFormat('fr-FR',{style:'currency',currency:'XAF',maximumFractionDigits:0}).format((n||0)/100);
export default function CrmCustomer360Page({customerId}) {
  const [data,setData]=useState(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const [op,setOp]=useState({title:'',pole:'Transversal',stage:'prospect',valueMinor:0}); const [activity,setActivity]=useState({type:'note',title:'',content:'',dueAt:''});
  const load=useCallback(async()=>{try{setData(await getCrmCustomer(customerId));}catch(e){setError(e.response?.data?.message||'Fiche inaccessible.');}},[customerId]); useEffect(()=>{load();},[load]);
  const submit=async(fn)=>{setBusy(true);setError('');try{await fn();await load();}catch(e){setError(e.response?.data?.message||'Action impossible.');}finally{setBusy(false);}};
  if(!data)return <main className="p-6">{error||'Chargement de la fiche Customer 360…'}</main>;
  const {customer,relations,communication,finance,opportunities,activities,timeline,dossiers}=data;
  return <main className="space-y-6 p-4 sm:p-6"><Link href={resolveWebDestination('CRM_CUSTOMERS')} className="inline-flex items-center gap-2 text-sm text-teal-700"><ArrowLeft size={16}/>Retour au CRM</Link>
    <header className="rounded-2xl bg-slate-900 p-6 text-white"><h1 className="text-2xl font-bold">{customer.displayName}</h1><p className="text-slate-300">{customer.company||'Personne'} · {customer.emails?.join(', ')||'sans email'} · {customer.phones?.join(', ')||'sans téléphone'}</p><div className="mt-3 flex flex-wrap gap-2">{customer.relations.map(r=><span key={r} className="rounded-full bg-white/10 px-3 py-1 text-xs">{r.replaceAll('_',' ')}</span>)}</div></header>
    {error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-800">{error}</p>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Chiffre d’affaires',money(finance.revenueMinor)],['Encours',money(finance.outstandingMinor)],['Remboursements',money(finance.refundsMinor)],['Dépenses',money(finance.expensesMinor)]].map(([l,v])=><div key={l} className="rounded-xl border bg-white p-4"><p className="text-xs uppercase text-slate-500">{l}</p><p className="mt-1 text-xl font-semibold">{v}</p></div>)}</section>
    <section className="grid gap-4 lg:grid-cols-3"><div className="rounded-xl border bg-white p-5 lg:col-span-2"><h2 className="font-semibold">Relations et dossier client</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{Object.entries(relations).map(([key,rows])=><div key={key} className="rounded-lg bg-slate-50 p-3"><p className="text-sm font-medium">{key.replaceAll('_',' ')}</p><p className="text-2xl font-bold">{rows.length}</p></div>)}</div><div className="mt-4"><p className="text-sm font-medium">Dossiers DOC-EVO référencés</p>{dossiers.length?<ul className="mt-2 list-inside list-disc text-sm">{dossiers.map((d,i)=><li key={`${d.domain}-${d.entityId}-${i}`}>{d.label} — {d.domain}</li>)}</ul>:<p className="text-sm text-slate-500">Aucun dossier relié.</p>}</div></div><div className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Communication</h2><p className="mt-3 flex gap-2"><MessageCircle size={18}/>{communication.conversations.length} conversation(s)</p><p>{communication.messages.length} message(s) récent(s)</p><p>{communication.notifications.length} notification(s)</p><p className="mt-3 text-sm text-slate-500">WhatsApp : préparé, aucun envoi implémenté.</p></div></section>
    <section className="rounded-xl border bg-white p-5"><h2 className="mb-4 flex items-center gap-2 font-semibold"><CircleDollarSign size={18}/>Pipeline commercial</h2><div className="overflow-x-auto"><div className="grid min-w-[1000px] grid-cols-8 gap-2">{STAGES.map(stage=><div key={stage} className="rounded-lg bg-slate-50 p-2"><p className="mb-2 text-xs font-semibold uppercase">{stage.replaceAll('_',' ')}</p>{opportunities.filter(o=>o.stage===stage).map(o=><article key={o._id} className="mb-2 rounded border bg-white p-2 text-xs"><b>{o.title}</b><p>{o.pole}</p><select aria-label={`Étape ${o.title}`} value={o.stage} onChange={e=>submit(()=>moveCrmOpportunity(o._id,e.target.value))} className="mt-2 w-full border">{STAGES.map(s=><option key={s}>{s}</option>)}</select></article>)}</div>)}</div></div><form onSubmit={e=>{e.preventDefault();submit(()=>createCrmOpportunity(customerId,{...op,valueMinor:Number(op.valueMinor)}));setOp({...op,title:''});}} className="mt-4 grid gap-2 sm:grid-cols-5"><input required placeholder="Nouvelle opportunité" value={op.title} onChange={e=>setOp({...op,title:e.target.value})} className="rounded border p-2 sm:col-span-2"/><select value={op.pole} onChange={e=>setOp({...op,pole:e.target.value})} className="rounded border p-2">{['Transversal','Altimmo','Accommodation','Hotel','Altcom','MilaEvents'].map(x=><option key={x}>{x}</option>)}</select><input type="number" min="0" placeholder="Valeur (centimes)" value={op.valueMinor} onChange={e=>setOp({...op,valueMinor:e.target.value})} className="rounded border p-2"/><button disabled={busy} className="rounded bg-teal-700 p-2 text-white"><Plus className="inline" size={16}/> Ajouter</button></form></section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border bg-white p-5"><h2 className="flex items-center gap-2 font-semibold"><CalendarPlus size={18}/>Activités</h2><form onSubmit={e=>{e.preventDefault();submit(()=>createCrmActivity(customerId,activity));setActivity({...activity,title:'',content:''});}} className="mt-3 grid gap-2"><select value={activity.type} onChange={e=>setActivity({...activity,type:e.target.value})} className="rounded border p-2">{['rendez_vous','tache','rappel','relance','note','appel','email','sms','whatsapp'].map(x=><option key={x}>{x.replaceAll('_',' ')}</option>)}</select><input required placeholder="Titre" value={activity.title} onChange={e=>setActivity({...activity,title:e.target.value})} className="rounded border p-2"/><textarea placeholder="Note" value={activity.content} onChange={e=>setActivity({...activity,content:e.target.value})} className="rounded border p-2"/><input type="datetime-local" value={activity.dueAt} onChange={e=>setActivity({...activity,dueAt:e.target.value})} className="rounded border p-2"/><button disabled={busy} className="rounded bg-slate-900 p-2 text-white">Créer l’activité</button></form>{activities.map(a=><div key={a._id} className="mt-3 flex items-center justify-between rounded bg-slate-50 p-3 text-sm"><div><b>{a.title}</b><p>{a.type.replaceAll('_',' ')} · {a.status}</p></div>{a.status!=='terminee'&&<button onClick={()=>submit(()=>updateCrmActivity(a._id,{status:'terminee'}))} className="text-teal-700">Terminer</button>}</div>)}</div><div className="rounded-xl border bg-white p-5"><h2 className="flex items-center gap-2 font-semibold"><FileText size={18}/>Timeline unifiée</h2><div className="mt-4 max-h-[650px] space-y-3 overflow-y-auto">{[...timeline].reverse().map((e,i)=><div key={`${e.date}-${e.type}-${i}`} className="border-l-2 border-teal-600 pl-3"><p className="text-sm font-medium">{e.label}</p><p className="text-xs text-slate-500">{new Date(e.date).toLocaleString('fr-FR')} · {e.type}</p></div>)}</div></div></section>
  </main>;
}
