"use client";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { toast } from "react-hot-toast";
import RoomAssignmentPanel from "../../components/RoomAssignmentPanel";
import { getHotelInventoryCalendar, rebuildHotelInventory, updateHotelInventoryRange } from "../../services/hotelService";
import { CalendarDays } from "lucide-react";
import { DashboardPage, DashboardPageHeader, DashboardState, DashboardToolbar } from "../../components/dashboard/DashboardUI";

const iso = (date) => date.toISOString().slice(0, 10);
const today = iso(new Date());
const statusLabels = { pending: "En attente", confirmed: "Confirmée", checked_in: "En séjour", checked_out: "Terminée", cancelled: "Annulée" };
const assignmentLabels = { unassigned: "Non affectée", partially_assigned: "Partielle", fully_assigned: "Complète" };
const sameDay = (value, expected) => value && iso(new Date(value)) === expected;

export default function HotelInventoryCalendarPage() {
  const { hotelId } = useParams(); const [from, setFrom] = useState(today); const [view, setView] = useState("week");
  const [data, setData] = useState({ days: [], reservations: [], rooms: [], housekeepingTasks: [], maintenanceTickets: [] }); const [loading, setLoading] = useState(false); const [selected, setSelected] = useState(null);
  const [filters, setFilters] = useState({ category: "", floor: "", status: "", assignment: "", arrivals: false, departures: false, unassigned: false, outOfService: false, stopSell: false, blocked: false, query: "" });
  const to = useMemo(() => { const date = new Date(`${from}T00:00:00Z`); date.setUTCDate(date.getUTCDate() + (view === "week" ? 7 : 31)); return iso(date); }, [from, view]);
  const load = useCallback(async (signal) => { setLoading(true); try { setData(await getHotelInventoryCalendar(hotelId, { from, to }, { signal })); } catch (error) { if (error.code !== "ERR_CANCELED") toast.error(error.response?.data?.message || "Calendrier indisponible."); } finally { if (!signal?.aborted) setLoading(false); } }, [hotelId, from, to]);
  useEffect(() => { const controller = new AbortController(); load(controller.signal); return () => controller.abort(); }, [load]);
  const categories = useMemo(() => [...new Map(data.days.map((day) => [String(day.roomCategory), { id: String(day.roomCategory), name: day.categoryName }])).values()], [data.days]);
  const floors = useMemo(() => [...new Set((data.rooms || []).map((room) => room.floor).filter((floor) => floor !== null && floor !== undefined))].sort((a, b) => a - b), [data.rooms]);
  const move = (direction) => { const date = new Date(`${from}T00:00:00Z`); date.setUTCDate(date.getUTCDate() + direction * (view === "week" ? 7 : 31)); setFrom(iso(date)); };
  const mutate = async (category, changes) => { try { await updateHotelInventoryRange(hotelId, { from, to, roomCategoryId: category.id, ...changes, reason: "Calendrier opérationnel Web" }); toast.success("Inventaire mis à jour."); load(); } catch (error) { toast.error(error.response?.data?.message || "Modification impossible."); } };
  const rebuild = async (category) => { try { await rebuildHotelInventory(hotelId, { from, to, roomCategoryId: category.id }); toast.success("Inventaire reconstruit."); load(); } catch (error) { toast.error(error.response?.data?.code === "INVENTORY_REBUILD_IN_PROGRESS" ? "Une reconstruction est déjà en cours pour cette période." : error.response?.data?.message || "Reconstruction impossible."); } };
  const query = filters.query.trim().toLowerCase();
  const visibleReservations = useMemo(() => data.reservations.filter((reservation) => {
    const rooms = reservation.assignedRooms || []; const guest = reservation.guest || {};
    const haystack = [reservation.reference, guest.firstName, guest.lastName, guest.phone, guest.email, reservation.roomCategory?.name, ...rooms.map((room) => room?.roomNumber)].filter(Boolean).join(" ").toLowerCase();
    return (!filters.category || String(reservation.roomCategory?._id || reservation.roomCategory) === filters.category)
      && (!filters.floor || rooms.some((room) => String(room?.floor) === filters.floor))
      && (!filters.status || reservation.status === filters.status)
      && (!filters.assignment || reservation.assignmentState === filters.assignment)
      && (!filters.arrivals || sameDay(reservation.checkInDate, today)) && (!filters.departures || sameDay(reservation.checkOutDate, today))
      && (!filters.unassigned || reservation.assignmentState !== "fully_assigned") && (!query || haystack.includes(query));
  }), [data.reservations, filters, query]);
  const visibleCategories = categories.filter((category) => !filters.category || category.id === filters.category);
  const resetFilters = () => setFilters({ category: "", floor: "", status: "", assignment: "", arrivals: false, departures: false, unassigned: false, outOfService: false, stopSell: false, blocked: false, query: "" });

  return <DashboardPage className="text-gray-900 dark:text-gray-100">
    <DashboardPageHeader icon={CalendarDays} title="Calendrier d’inventaire" description="Pilotez disponibilités, affectations et opérations sur une même période." />
    <DashboardToolbar label="Navigation de période"><button onClick={() => move(-1)} className="border rounded px-3 py-2 focus:ring-2" aria-label="Période précédente">←</button><button onClick={() => setFrom(today)} className="border rounded px-3 py-2">Aujourd’hui</button><button onClick={() => move(1)} className="border rounded px-3 py-2 focus:ring-2" aria-label="Période suivante">→</button><button aria-pressed={view === "week"} onClick={() => setView("week")} className="border rounded px-3 py-2">Semaine</button><button aria-pressed={view === "month"} onClick={() => setView("month")} className="border rounded px-3 py-2">Mois</button><input aria-label="Date de début" type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="border rounded px-3 py-2 bg-transparent" /></DashboardToolbar>
    <DashboardToolbar className="grid sm:grid-cols-2 lg:grid-cols-4" label="Filtres du calendrier">
      <input aria-label="Rechercher une réservation" placeholder="Référence, client, téléphone, email, chambre…" value={filters.query} onChange={(e) => setFilters((f) => ({ ...f, query: e.target.value }))} className="border rounded px-3 py-2 bg-transparent lg:col-span-2" />
      <select aria-label="Filtrer par catégorie" value={filters.category} onChange={(e) => setFilters((f) => ({ ...f, category: e.target.value }))} className="border rounded px-3 py-2 bg-white dark:bg-gray-900"><option value="">Toutes les catégories</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
      <select aria-label="Filtrer par étage" value={filters.floor} onChange={(e) => setFilters((f) => ({ ...f, floor: e.target.value }))} className="border rounded px-3 py-2 bg-white dark:bg-gray-900"><option value="">Tous les étages</option>{floors.map((floor) => <option key={floor} value={floor}>Étage {floor}</option>)}</select>
      <select aria-label="Filtrer par statut" value={filters.status} onChange={(e) => setFilters((f) => ({ ...f, status: e.target.value }))} className="border rounded px-3 py-2 bg-white dark:bg-gray-900"><option value="">Tous les statuts</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>
      <select aria-label="Filtrer par affectation" value={filters.assignment} onChange={(e) => setFilters((f) => ({ ...f, assignment: e.target.value }))} className="border rounded px-3 py-2 bg-white dark:bg-gray-900"><option value="">Toutes les affectations</option>{Object.entries(assignmentLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>
      {[['arrivals', 'Arrivées aujourd’hui'], ['departures', 'Départs aujourd’hui'], ['unassigned', 'Affectations incomplètes'], ['outOfService', 'Hors service'], ['stopSell', 'Stop-sell'], ['blocked', 'Stock bloqué']].map(([key, label]) => <label key={key} className="flex items-center gap-2 min-h-11"><input type="checkbox" checked={filters[key]} onChange={(e) => setFilters((f) => ({ ...f, [key]: e.target.checked }))} />{label}</label>)}
      <button onClick={resetFilters} className="border rounded px-3 py-2">Réinitialiser</button>
    </DashboardToolbar>
    <aside aria-label="Légende" className="flex flex-wrap gap-3 text-xs mb-4"><span>⏳ En attente</span><span>✅ Confirmée</span><span>🔑 En séjour</span><span>🧹 Nettoyage</span><span>🔎 Inspection</span><span>⛔ Hors service</span><span>⚠ Affectation partielle</span><span>🚫 Vente fermée</span></aside>
    {loading ? <DashboardState type="loading" title="Chargement du calendrier…" /> : visibleCategories.map((category) => {
      const categoryDays = data.days.filter((day) => String(day.roomCategory) === category.id && (!filters.stopSell || day.stopSell) && (!filters.blocked || day.blockedUnits > 0) && (!filters.outOfService || day.physicalOutOfService > 0));
      if (!categoryDays.length && (filters.stopSell || filters.blocked || filters.outOfService)) return null;
      return <section key={category.id} className="mb-6 rounded-xl border dark:border-gray-700 overflow-hidden"><header className="flex flex-wrap gap-2 items-center p-3 bg-gray-50 dark:bg-gray-800"><h2 className="font-semibold mr-auto">{category.name}</h2><button onClick={() => mutate(category, { stopSell: true })} className="text-sm border rounded px-2 py-1">🚫 Stop-sell</button><button onClick={() => mutate(category, { stopSell: false, isClosed: false })} className="text-sm border rounded px-2 py-1">✅ Rouvrir</button><button onClick={() => { const value = window.prompt("Unités bloquées", "0"); if (value !== null) mutate(category, { blockedUnits: Number(value) }); }} className="text-sm border rounded px-2 py-1">⛔ Bloquer</button><button onClick={() => rebuild(category)} className="text-sm border rounded px-2 py-1">↻ Reconstruire</button></header><div className="overflow-x-auto" tabIndex="0" aria-label={`Inventaire ${category.name}`}><div className="flex min-w-max">{categoryDays.map((day) => <article key={day.id} title={`${day.availableUnits} disponibles, ${day.reservedUnits} réservées`} className={`w-40 border-r p-3 ${day.stopSell || day.isClosed ? "bg-red-50 dark:bg-red-950" : ""}`}><p className="text-xs font-medium">{new Date(day.date).toLocaleDateString("fr-FR", { weekday: "short", day: "2-digit", month: "2-digit" })}</p><p className="text-xl font-bold">{day.availableUnits} libre(s)</p><p className="text-xs">✅ réservé {day.reservedUnits}</p><p className="text-xs">⛔ bloqué {day.blockedUnits}</p><p className="text-xs">🔧 hors service {day.physicalOutOfService}</p>{(day.stopSell || day.isClosed) && <p className="text-xs text-red-700 dark:text-red-300">🚫 Vente fermée</p>}</article>)}</div></div></section>;
    })}
    <section className="rounded-xl border dark:border-gray-700 p-3"><h2 className="font-semibold mb-2">Arrivées, départs et affectations ({visibleReservations.length})</h2>{!visibleReservations.length && <p>Aucune réservation ne correspond aux filtres.</p>}{visibleReservations.map((reservation) => <article id={`reservation-${reservation._id}`} key={reservation._id} className={`border-b py-3 ${selected?._id === reservation._id ? "ring-2 ring-blue-500 rounded p-2" : ""}`}><button className="text-left w-full focus:ring-2 rounded" onClick={() => setSelected(selected?._id === reservation._id ? null : reservation)} aria-expanded={selected?._id === reservation._id}><strong>{reservation.reference}</strong> — {statusLabels[reservation.status] || reservation.status} — {assignmentLabels[reservation.assignmentState] || reservation.assignmentState} — {reservation.assignedRooms?.map((room) => room?.roomNumber).filter(Boolean).join(", ") || "aucune chambre"}</button>{selected?._id === reservation._id && <div className="mt-2"><p>{reservation.guest?.firstName} {reservation.guest?.lastName} · {reservation.guest?.email || reservation.guest?.phone}</p><RoomAssignmentPanel reservation={reservation} onChanged={() => load()} /></div>}</article>)}</section>
    <section className="mt-4 grid md:grid-cols-3 gap-3" aria-label="État opérationnel des chambres">{(data.rooms || []).filter((room) => !filters.floor || String(room.floor) === filters.floor).map((room) => <article key={room._id} className="border rounded p-2"><strong>Chambre {room.roomNumber}</strong><p>{room.status === 'out_of_service' ? '⛔' : room.status === 'cleaning' ? '🧹' : room.status === 'inspection' ? '🔎' : room.status === 'occupied' ? '🔑' : '✅'} {room.status} · étage {room.floor ?? '—'}</p><div className="flex gap-3 mt-1 text-sm"><a className="underline" href={`/dashboard/hotels/${hotelId}/housekeeping`}>Ménage</a><a className="underline" href={`/dashboard/hotels/${hotelId}/maintenance`}>Maintenance</a></div></article>)}</section>
  </DashboardPage>;
}
