'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { ClipboardList, Search, X } from 'lucide-react';
import { acceptRealEstateApplication, getRealEstateApplication, getRealEstateReservation, listRealEstateApplications, rejectRealEstateApplication, reviewRealEstateApplication } from '../../services/realEstateApplicationService';
import { DashboardCard, DashboardPage, DashboardPageHeader, DashboardPagination, DashboardState, DashboardTableContainer, DashboardToolbar } from '../../components/dashboard/DashboardUI';

const STATUS = { submitted: 'Soumis', under_review: 'En étude', accepted: 'Accepté', rejected: 'Rejeté', withdrawn: 'Retiré', expired: 'Expiré', not_selected: 'Non retenu' };
const money = (value, currency = 'XAF') => value == null ? '—' : new Intl.NumberFormat('fr-FR', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value);

export default function RealEstateApplicationsPage() {
  const [filters, setFilters] = useState({ kind: '', status: '', search: '', sort: 'newest' });
  const [page, setPage] = useState(1); const [data, setData] = useState({ applications: [], pagination: { pages: 1 } });
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState(null); const [reservation, setReservation] = useState(null); const [compare, setCompare] = useState([]); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await listRealEstateApplications({ ...filters, page, limit: 20 })); } catch (e) { setError(e.response?.data?.message || 'Chargement impossible.'); } finally { setLoading(false); } }, [filters, page]);
  useEffect(() => { load(); }, [load]);
  const open = async (id) => { setBusy(true); try { const row = await getRealEstateApplication(id); setSelected(row); setReservation(row.reservation ? await getRealEstateReservation(row.reservation) : null); } catch (e) { setError(e.response?.data?.message || 'Dossier indisponible.'); } finally { setBusy(false); } };
  const decide = async (action) => { if (!selected || busy) return; setBusy(true); setError(''); try { if (action === 'review') await reviewRealEstateApplication(selected._id); if (action === 'accept') { if (!window.confirm('Accepter ce dossier et réserver temporairement le bien ?')) return; await acceptRealEstateApplication(selected._id, `web:${selected._id}:${crypto.randomUUID()}`); } if (action === 'reject') { const reason = window.prompt('Motif du rejet (obligatoire) :'); if (!reason?.trim()) return; await rejectRealEstateApplication(selected._id, reason.trim()); } await open(selected._id); await load(); } catch (e) { setError(e.response?.data?.message || 'Décision impossible.'); } finally { setBusy(false); } };
  const compared = useMemo(() => data.applications.filter((row) => compare.includes(row._id)), [compare, data.applications]);
  return <DashboardPage>
    <DashboardPageHeader icon={ClipboardList} eyebrow="Altimmo · IM-2" title="Offres et candidatures" description="Étudiez, comparez et décidez les dossiers immobiliers." />
    <DashboardToolbar><label className="flex min-w-48 items-center gap-2"><Search className="h-4 w-4"/><span className="sr-only">Rechercher</span><input value={filters.search} onChange={(e) => { setPage(1); setFilters({ ...filters, search: e.target.value }); }} placeholder="Rechercher un bien" /></label><select aria-label="Type de dossier" value={filters.kind} onChange={(e) => { setPage(1); setFilters({ ...filters, kind: e.target.value }); }}><option value="">Tous les types</option><option value="purchase_offer">Offres d’achat</option><option value="rental_application">Candidatures locatives</option></select><select aria-label="Statut" value={filters.status} onChange={(e) => { setPage(1); setFilters({ ...filters, status: e.target.value }); }}><option value="">Tous les statuts</option>{Object.entries(STATUS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Tri" value={filters.sort} onChange={(e) => setFilters({ ...filters, sort: e.target.value })}><option value="newest">Plus récents</option><option value="oldest">Plus anciens</option><option value="amount_desc">Montant décroissant</option><option value="amount_asc">Montant croissant</option></select></DashboardToolbar>
    {loading ? <DashboardState type="loading" title="Chargement des dossiers…"/> : error && !data.applications.length ? <DashboardState type="error" title="Dossiers indisponibles" description={error} action={<button onClick={load}>Réessayer</button>}/> : !data.applications.length ? <DashboardState title="Aucun dossier" description="Aucun dossier ne correspond aux filtres."/> : <>{error && <p role="alert" className="mb-4 rounded bg-red-50 p-3 text-red-800">{error}</p>}<DashboardTableContainer label="Liste des offres et candidatures"><table className="w-full min-w-[760px]"><thead><tr><th>Comparer</th><th>Bien</th><th>Candidat</th><th>Type</th><th>Montant / entrée</th><th>Statut</th><th>Action</th></tr></thead><tbody>{data.applications.map((row) => <tr key={row._id}><td><input type="checkbox" aria-label={`Comparer ${row.property?.title}`} checked={compare.includes(row._id)} disabled={!compare.includes(row._id) && compare.length >= 4} onChange={() => setCompare((values) => values.includes(row._id) ? values.filter((id) => id !== row._id) : [...values, row._id])}/></td><td>{row.property?.title || 'Bien supprimé'}</td><td>{row.applicant?.name || [row.applicant?.firstName, row.applicant?.lastName].filter(Boolean).join(' ') || 'Client'}</td><td>{row.kind === 'purchase_offer' ? 'Offre' : 'Candidature'}</td><td>{row.kind === 'purchase_offer' ? money(row.purchaseOffer?.amount, row.purchaseOffer?.currency) : row.rentalApplication?.desiredMoveIn ? new Date(row.rentalApplication.desiredMoveIn).toLocaleDateString('fr-FR') : '—'}</td><td>{STATUS[row.status] || row.status}</td><td><button onClick={() => open(row._id)}>Consulter</button></td></tr>)}</tbody></table></DashboardTableContainer><DashboardPagination page={page} totalPages={data.pagination?.pages || 1} onPrevious={() => setPage((v) => v - 1)} onNext={() => setPage((v) => v + 1)}/></>}
    {compared.length > 1 && <DashboardCard className="mt-6"><h2 className="mb-3 text-lg font-semibold">Comparaison ({compared.length})</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{compared.map((row) => <div key={row._id} className="rounded border p-3"><strong>{row.applicant?.name || 'Candidat'}</strong><p>{row.kind === 'purchase_offer' ? money(row.purchaseOffer?.amount, row.purchaseOffer?.currency) : `${row.rentalApplication?.occupants || '—'} occupant(s)`}</p><p>{STATUS[row.status]}</p></div>)}</div></DashboardCard>}
    {selected && <div role="dialog" aria-modal="true" aria-labelledby="application-title" className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white p-6"><div className="flex justify-between"><h2 id="application-title" className="text-xl font-semibold">{selected.property?.title}</h2><button aria-label="Fermer" onClick={() => setSelected(null)}><X/></button></div><dl className="mt-5 grid gap-3 sm:grid-cols-2"><div><dt>Statut</dt><dd>{STATUS[selected.status]}</dd></div><div><dt>Validité</dt><dd>{new Date(selected.validUntil).toLocaleString('fr-FR')}</dd></div><div><dt>Candidat</dt><dd>{selected.applicant?.name || selected.applicant?.email}</dd></div><div><dt>Pièces privées</dt><dd>{selected.attachments?.length || 0}</dd></div></dl><p className="mt-4 whitespace-pre-wrap">{selected.message || 'Aucun message.'}</p>{reservation && <div className="mt-5 rounded bg-blue-50 p-4"><strong>Réservation {reservation.status}</strong><p>Expiration : {new Date(reservation.expiresAt).toLocaleString('fr-FR')}</p></div>}<h3 className="mt-6 font-semibold">Historique</h3><ol className="mt-2 space-y-2">{selected.history?.map((item, index) => <li key={`${item.at}-${index}`} className="border-l-2 pl-3"><strong>{item.action}</strong> — {new Date(item.at).toLocaleString('fr-FR')}{item.reason && <p>{item.reason}</p>}</li>)}</ol>{['submitted', 'under_review'].includes(selected.status) && <div className="mt-6 flex flex-wrap gap-3">{selected.status === 'submitted' && <button disabled={busy} onClick={() => decide('review')}>Mettre en étude</button>}<button disabled={busy} onClick={() => decide('accept')} className="rounded bg-green-700 px-4 py-2 text-white">Accepter</button><button disabled={busy} onClick={() => decide('reject')} className="rounded bg-red-700 px-4 py-2 text-white">Rejeter</button></div>}</div></div>}
  </DashboardPage>;
}
