const router = require('express').Router();
const auth = require('../controllers/authController');
const ctrl = require('../controllers/accommodationReservationController');

router.use(auth.protect);
router.post('/', ctrl.create);
router.get('/', ctrl.list);
router.get('/:id', ctrl.getOne);
router.post('/:id/confirm', ctrl.transition('confirmed'));
router.post('/:id/cancel', ctrl.transition('cancelled'));
router.post('/:id/check-in', ctrl.transition('checked_in'));
router.post('/:id/check-out', ctrl.transition('checked_out'));
router.post('/:id/no-show', ctrl.transition('no_show'));
router.get('/:id/financial-summary', ctrl.financialSummary);
router.post('/:id/payments', ctrl.createPayment);
router.post('/payments/:paymentId/confirm', ctrl.confirmPayment);
router.post('/allocations/:allocationId/reverse', ctrl.reversePaymentAllocation);
router.get('/:id/refundable-summary', ctrl.refundableSummary);
router.post('/:id/refunds', ctrl.requestRefund);
router.post('/refunds/:refundId/approve', ctrl.approveRefund);
router.post('/refunds/:refundId/complete', ctrl.completeRefund);
router.post('/refunds/:refundId/cancel', ctrl.cancelRefund);
module.exports = router;
