const router = require('express').Router();
const auth = require('../controllers/authController');
const ctrl = require('../controllers/accommodationReservationController');
const { requireTenantScopeForStaffAllowPlatformWide } = require('../middleware/tenantContext');

router.use(auth.protect);
router.post('/', ctrl.create);
router.get('/', requireTenantScopeForStaffAllowPlatformWide, ctrl.list);
router.get('/:id', ctrl.getOne);
router.post('/:id/confirm', requireTenantScopeForStaffAllowPlatformWide, ctrl.transition('confirmed'));
router.post('/:id/cancel', requireTenantScopeForStaffAllowPlatformWide, ctrl.transition('cancelled'));
router.post('/:id/check-in', requireTenantScopeForStaffAllowPlatformWide, ctrl.transition('checked_in'));
router.post('/:id/check-out', requireTenantScopeForStaffAllowPlatformWide, ctrl.transition('checked_out'));
router.post('/:id/no-show', requireTenantScopeForStaffAllowPlatformWide, ctrl.transition('no_show'));
router.get('/:id/financial-summary', ctrl.financialSummary);
router.post('/:id/payments', ctrl.createPayment);
router.post('/payments/:paymentId/confirm', ctrl.confirmPayment);
router.post('/allocations/:allocationId/reverse', ctrl.reversePaymentAllocation);
router.get('/refunds/operations', requireTenantScopeForStaffAllowPlatformWide, ctrl.listRefundOperations);
router.get('/deductions/operations', requireTenantScopeForStaffAllowPlatformWide, ctrl.listDeductionOperations);
router.post('/deductions/:deductionId/approve', requireTenantScopeForStaffAllowPlatformWide, ctrl.approveDeduction);
router.post('/deductions/:deductionId/reject', requireTenantScopeForStaffAllowPlatformWide, ctrl.rejectDeduction);
router.get('/:id/refundable-summary', ctrl.refundableSummary);
router.get('/:id/deductions', requireTenantScopeForStaffAllowPlatformWide, ctrl.listDeductions);
router.post('/:id/deductions', requireTenantScopeForStaffAllowPlatformWide, ctrl.reportDeduction);
router.post('/:id/refunds', ctrl.requestRefund);
router.post('/refunds/:refundId/approve', requireTenantScopeForStaffAllowPlatformWide, ctrl.approveRefund);
router.post('/refunds/:refundId/complete', requireTenantScopeForStaffAllowPlatformWide, ctrl.completeRefund);
router.post('/refunds/:refundId/cancel', requireTenantScopeForStaffAllowPlatformWide, ctrl.cancelRefund);
module.exports = router;
