const express = require('express');
const auth = require('../controllers/authController');
const ctrl = require('../controllers/financialController');
const dashboardCtrl = require('../controllers/hotelFinancialDashboardController');
const { STAFF_IMMO } = require('../utils/roles');
const router = express.Router();
router.use(auth.protect);
// DOC-ARCH-2 — lecture seule, gardée au niveau route (pas d'établissement
// précis à vérifier ici, contrairement aux routes /hotel/:hotelId/*).
router.get('/accommodations/documents', auth.restrictTo(...STAFF_IMMO), ctrl.listAccommodationDocuments);
router.get('/hotel/dashboard/summary', dashboardCtrl.getSummary);
router.get('/hotel/dashboard/trends', dashboardCtrl.getTrends);
router.get('/hotel/dashboard/breakdown', dashboardCtrl.getBreakdown);
router.get('/hotel/dashboard/aging', dashboardCtrl.getAging);
router.get('/hotel/dashboard/alerts', dashboardCtrl.getAlerts);
router.post('/hotel/reservations/:reservationId/invoice-draft', ctrl.createHotelDraft);
router.get('/hotel/reservations/:reservationId/document', ctrl.getReservationDocument);
router.get('/hotel/:hotelId/documents', ctrl.listHotelDocuments);
router.get('/documents/:documentId', ctrl.getDocument);
router.patch('/documents/:documentId/draft', ctrl.updateDraft);
router.post('/documents/:documentId/finalize-lines', ctrl.finalizeLines);
router.post('/documents/:documentId/refresh-from-reservation', ctrl.refreshFromReservation);
router.post('/documents/:documentId/issue', ctrl.issue);
router.post('/documents/:documentId/pdf', ctrl.generateOfficialPdf);
router.get('/documents/:documentId/pdf', ctrl.getOfficialPdfStatus);
router.get('/documents/:documentId/pdf/download', ctrl.downloadOfficialPdf);
router.post('/documents/:documentId/email', ctrl.sendOfficialInvoiceEmail);
router.get('/documents/:documentId/deliveries', ctrl.listDocumentDeliveries);
router.post('/payments/manual', ctrl.createManualPayment);
router.post('/hotel/payments', ctrl.createHotelPayment);
router.get('/hotel/:hotelId/payments', ctrl.listHotelPayments);
router.get('/hotel/reservations/:reservationId/payments', ctrl.listReservationPayments);
router.get('/documents/:documentId/payments', ctrl.listDocumentPayments);
router.get('/payments/:paymentId', ctrl.getPayment);
router.post('/payments/:paymentId/confirm', ctrl.confirmPayment);
router.post('/payments/:paymentId/allocations', ctrl.allocateHotelPayment);
router.post('/allocations', ctrl.allocate);
router.post('/allocations/:allocationId/reverse', ctrl.reverseAllocation);
router.post('/hotel/allocations/:allocationId/reverse', ctrl.reverseHotelAllocation);
router.get('/documents/:documentId/ledger', ctrl.getLedger);
module.exports = router;
