const express = require('express');
const auth = require('../controllers/authController');
const ctrl = require('../controllers/rentalManagementController');
const { ROLES_GL } = require('../utils/roles');

const router = express.Router();
router.use(auth.protect);
router.get('/owner/my', auth.restrictTo('Proprietaire'), ctrl.ownerList);
router.post('/:id/owner/:action', auth.restrictTo('Proprietaire'), ctrl.ownerRequest);
router.get('/onboarding/options', auth.restrictTo('Admin', 'GestionnaireImmobilier'), ctrl.onboardingOptions);
router.post('/onboarding', auth.restrictTo('Admin', 'GestionnaireImmobilier'), ctrl.onboard);
router.use(auth.restrictTo(...ROLES_GL));
router.get('/stats', ctrl.stats);
router.get('/', ctrl.list);
router.post('/', ctrl.create);
router.get('/:id', ctrl.getOne);
router.patch('/:id', ctrl.update);
router.post('/:id/deactivate', auth.restrictTo('Admin', 'GestionnaireImmobilier'), ctrl.deactivate);
router.get('/:id/history', ctrl.history);
router.post('/:id/publish', ctrl.publish);
router.post('/:id/suspend-listing', ctrl.suspend);
router.post('/:id/mark-rented', ctrl.markRented);
router.post('/:id/mark-vacant', ctrl.markVacant);
router.post('/:id/maintenance', ctrl.markMaintenance);
router.post('/:id/complete-maintenance', ctrl.completeMaintenance);
router.post('/:id/start-notice', ctrl.startNotice);
router.post('/:id/acknowledge-notice', ctrl.acknowledgeNotice);
router.post('/:id/cancel-notice', ctrl.cancelNotice);
router.post('/:id/validate-exit', ctrl.validateExitInspection);
router.post('/:id/requests/:requestId/resolve', ctrl.resolveRequest);

module.exports = router;
