const mongoose = require('mongoose');
const { startFinancialMongo, clearFinancialMongo, stopFinancialMongo } = require('./helpers/financialMongoEnvironment');
const FinancialDocument = require('../models/FinancialDocument');
const FinancialPayment = require('../models/FinancialPayment');
const FinancialPaymentReceipt = require('../models/FinancialPaymentReceipt');
const FinancialLedgerEntry = require('../models/FinancialLedgerEntry');
const { createHotelPayment, confirmHotelPayment, rejectManualHotelPayment } = require('../services/finance/financialPaymentService');
const { allocatePaymentToDocument, reversePaymentAllocation } = require('../services/finance/paymentAllocationService');
const { generatePaymentReceipt } = require('../services/finance/manualPaymentReceiptService');

jest.setTimeout(120000); const id = () => new mongoose.Types.ObjectId();
async function fixture() { const actor = { id: id() }; const hotelId = id(); const reservationId = id(); const document = await FinancialDocument.create({ domain: 'hotel', establishmentType: 'Hotel', establishmentId: hotelId, documentType: 'invoice', documentNumber: `FAC-${id()}`, status: 'issued', paymentStatus: 'unpaid', currency: 'XAF', subjectType: 'HotelReservation', subjectId: reservationId, totalMinor: 100000, balanceMinor: 100000, amountAllocatedMinor: 0, businessOperationKey: `doc-${id()}`, metadata: { source: 'hotel_reservation', linesFinalized: true }, createdBy: actor.id, issuedBy: actor.id, issuedAt: new Date() }); return { actor, hotelId, reservationId, document }; }
async function payment(f, key = 'create') { return (await createHotelPayment({ data: { establishmentId: f.hotelId, documentId: f.document._id, reservationId: f.reservationId, amountMinor: 40000, currency: 'XAF', method: 'bank_transfer', reference: 'VIR-42' }, actor: f.actor, businessOperationKey: key, transactionMode: 'transactional' })).payment; }
const fakeStorage = { uploadPrivateAsset: jest.fn(async (buffer) => ({ assetClass: 'PRIVATE_DOCUMENT', purpose: 'financial', provider: 'cloudinary', publicId: `private/${Math.random()}`, resourceType: 'raw', deliveryType: 'authenticated', format: 'pdf', mimeType: 'application/pdf', originalFilename: 'receipt.pdf', size: buffer.length })), deletePrivateAsset: jest.fn(async () => ({})) };
beforeAll(startFinancialMongo); afterEach(async () => { jest.clearAllMocks(); await clearFinancialMongo(); }); afterAll(stopFinancialMongo);

test('double rejet est idempotent, motivé et n’alloue rien', async () => { const f = await fixture(); const p = await payment(f); const results = await Promise.all([rejectManualHotelPayment({ paymentId: p._id, actor: f.actor, reason: 'Virement non reçu', businessOperationKey: 'reject', transactionMode: 'transactional' }), rejectManualHotelPayment({ paymentId: p._id, actor: f.actor, reason: 'Virement non reçu', businessOperationKey: 'reject', transactionMode: 'transactional' })]); expect(results.filter((r) => r.rejected)).toHaveLength(1); expect(await FinancialPayment.findById(p._id)).toMatchObject({ status: 'failed', manualValidation: { status: 'rejected', reason: 'Virement non reçu' }, allocatedAmountMinor: 0 }); expect(await FinancialLedgerEntry.countDocuments({ entityId: p._id, eventType: 'payment.rejected' })).toBe(1); await expect(confirmHotelPayment({ paymentId: p._id, actor: f.actor, businessOperationKey: 'late-confirm', transactionMode: 'transactional' })).rejects.toMatchObject({ code: 'FINANCIAL_PAYMENT_INVALID_TRANSITION' }); });
test('confirmation et rejet concurrents produisent un seul état terminal et un seul ledger terminal', async () => { const f = await fixture(); const p = await payment(f); await Promise.allSettled([confirmHotelPayment({ paymentId: p._id, actor: f.actor, businessOperationKey: 'race-confirm', transactionMode: 'transactional' }), rejectManualHotelPayment({ paymentId: p._id, actor: f.actor, reason: 'Contrôle négatif', businessOperationKey: 'race-reject', transactionMode: 'transactional' })]); const current = await FinancialPayment.findById(p._id); expect(['succeeded', 'failed']).toContain(current.status); expect(await FinancialLedgerEntry.countDocuments({ entityId: p._id, eventType: { $in: ['payment.confirmed', 'payment.rejected'] } })).toBe(1); });
test('un seul reçu stable est créé en concurrence et survit au renversement', async () => { const f = await fixture(); const p = await payment(f); await confirmHotelPayment({ paymentId: p._id, actor: f.actor, businessOperationKey: 'confirm', transactionMode: 'transactional' }); const allocation = await allocatePaymentToDocument({ paymentId: p._id, documentId: f.document._id, amountMinor: 40000, businessOperationKey: 'allocate', actor: f.actor, transactionMode: 'transactional' }); const results = await Promise.all([generatePaymentReceipt({ paymentId: p._id, actor: f.actor, storageService: fakeStorage }), generatePaymentReceipt({ paymentId: p._id, actor: f.actor, storageService: fakeStorage })]); expect(new Set(results.map((r) => r.receipt.receiptNumber)).size).toBe(1); expect(await FinancialPaymentReceipt.countDocuments({ financialPayment: p._id })).toBe(1); const number = results[0].receipt.receiptNumber; await reversePaymentAllocation({ allocationId: allocation._id, reason: 'Correction', businessOperationKey: 'reverse', actor: f.actor, transactionMode: 'transactional' }); expect((await FinancialPaymentReceipt.findOne({ financialPayment: p._id })).receiptNumber).toBe(number); });
test('aucun reçu pour un paiement pending ou confirmé non alloué', async () => { const f = await fixture(); const p = await payment(f); await expect(generatePaymentReceipt({ paymentId: p._id, actor: f.actor, storageService: fakeStorage })).rejects.toMatchObject({ code: 'FINANCIAL_RECEIPT_PAYMENT_NOT_CONFIRMED' }); await confirmHotelPayment({ paymentId: p._id, actor: f.actor, businessOperationKey: 'confirm', transactionMode: 'transactional' }); await expect(generatePaymentReceipt({ paymentId: p._id, actor: f.actor, storageService: fakeStorage })).rejects.toMatchObject({ code: 'FINANCIAL_RECEIPT_ALLOCATION_REQUIRED' }); });
