import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, RefreshControl, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useFocusEffect } from '@react-navigation/native';
import { getMyApplications, withdrawApplication } from '../../services/realEstateApplicationService';
import { colors, fonts, fontSize, spacing } from '../../theme';

const labels = { submitted: 'Soumis', under_review: 'En étude', accepted: 'Accepté', rejected: 'Rejeté', withdrawn: 'Retiré', expired: 'Expiré', not_selected: 'Non retenu' };
export default function RealEstateApplicationsScreen({ navigation }) {
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { setError(''); try { setRows(await getMyApplications()); } catch (e) { setError(e.normalized?.message || 'Chargement impossible.'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useFocusEffect(useCallback(() => { setLoading(true); load(); }, [load]));
  const withdraw = (row) => Alert.alert('Retirer le dossier', 'Cette action est définitive.', [{ text: 'Annuler', style: 'cancel' }, { text: 'Retirer', style: 'destructive', onPress: async () => { try { await withdrawApplication(row._id); await load(); } catch (e) { Alert.alert('Erreur', e.response?.data?.message || 'Retrait impossible.'); } } }]);
  if (loading) return <View style={styles.center}><ActivityIndicator color={colors.gold}/></View>;
  return <SafeAreaView style={styles.safe}><View style={styles.header}><TouchableOpacity onPress={() => navigation.goBack()} accessibilityLabel="Retour"><Text style={styles.back}>‹</Text></TouchableOpacity><Text style={styles.title}>Mes dossiers</Text></View>{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<FlatList data={rows} keyExtractor={(item) => item._id} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); load(); }}/>} ListEmptyComponent={<Text style={styles.empty}>Aucun dossier immobilier.</Text>} renderItem={({ item }) => <TouchableOpacity style={styles.card} onPress={() => navigation.navigate('RealEstateApplicationDetail', { applicationId: item._id })}><Text style={styles.cardTitle}>{item.property?.title || 'Bien immobilier'}</Text><Text style={styles.status}>{labels[item.status] || item.status}</Text><Text style={styles.meta}>{item.kind === 'purchase_offer' ? 'Offre d’achat' : 'Candidature locative'}</Text>{['submitted', 'under_review'].includes(item.status) && <TouchableOpacity onPress={() => withdraw(item)}><Text style={styles.withdraw}>Retirer</Text></TouchableOpacity>}</TouchableOpacity>}/></SafeAreaView>;
}
const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:colors.bg},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.bg},header:{flexDirection:'row',alignItems:'center',gap:spacing.md,padding:spacing.lg},back:{fontSize:36,color:colors.gold},title:{fontFamily:fonts.display,fontSize:fontSize.xxl,color:colors.text},list:{padding:spacing.lg,gap:spacing.md},card:{padding:spacing.lg,borderWidth:1,borderColor:colors.borderGold,backgroundColor:colors.bgCard,borderRadius:12},cardTitle:{fontFamily:fonts.bodyBold,fontSize:fontSize.lg,color:colors.text},status:{color:colors.gold,marginTop:6},meta:{color:colors.textMuted,marginTop:4},withdraw:{color:'#EF4444',marginTop:spacing.md,fontFamily:fonts.bodyMedium},empty:{textAlign:'center',color:colors.textMuted,marginTop:60},error:{color:'#EF4444',paddingHorizontal:spacing.lg}});
