import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useFocusEffect } from '@react-navigation/native';
import { getApplication, getReservation } from '../../services/realEstateApplicationService';
import { colors, fonts, fontSize, spacing } from '../../theme';
const labels = { submitted: 'Soumis', under_review: 'En étude', accepted: 'Accepté', rejected: 'Rejeté', withdrawn: 'Retiré', expired: 'Expiré', not_selected: 'Non retenu' };
export default function RealEstateApplicationDetailScreen({ route, navigation }) { const [row,setRow]=useState(null); const [reservation,setReservation]=useState(null); const [loading,setLoading]=useState(true); const load=useCallback(async()=>{try{const item=await getApplication(route.params.applicationId);setRow(item);setReservation(item.reservation?await getReservation(item.reservation):null);}catch(e){Alert.alert('Erreur',e.response?.data?.message||'Dossier indisponible.');}finally{setLoading(false);}},[route.params.applicationId]); useFocusEffect(useCallback(()=>{load();},[load])); if(loading)return <View style={styles.center}><ActivityIndicator color={colors.gold}/></View>; if(!row)return null; return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.body}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={styles.back}>‹ Retour</Text></TouchableOpacity><Text style={styles.title}>{row.property?.title}</Text><Text style={styles.status}>{labels[row.status]||row.status}</Text><Text style={styles.text}>{row.message||'Aucun message.'}</Text>{reservation&&<View style={styles.reservation}><Text style={styles.section}>Réservation {reservation.status}</Text><Text style={styles.text}>Expire le {new Date(reservation.expiresAt).toLocaleString('fr-FR')}</Text>{reservation.transaction&&<TouchableOpacity onPress={()=>navigation.navigate('Transactions')}><Text style={styles.link}>Poursuivre vers la transaction</Text></TouchableOpacity>}</View>}<Text style={styles.section}>Historique</Text>{row.history?.map((item,index)=><View key={`${item.at}-${index}`} style={styles.history}><Text style={styles.text}>{item.action}</Text><Text style={styles.muted}>{new Date(item.at).toLocaleString('fr-FR')}</Text></View>)}</ScrollView></SafeAreaView>; }
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.bg},body:{padding:spacing.lg,gap:spacing.md},back:{color:colors.gold,fontFamily:fonts.bodyMedium},title:{fontFamily:fonts.display,fontSize:fontSize.xxl,color:colors.text},status:{color:colors.gold,fontFamily:fonts.bodyBold},text:{color:colors.text,fontFamily:fonts.body},muted:{color:colors.textMuted},section:{color:colors.text,fontFamily:fonts.bodyBold,fontSize:fontSize.lg,marginTop:spacing.md},reservation:{padding:spacing.lg,borderColor:colors.borderGold,borderWidth:1,borderRadius:12},link:{color:colors.gold,marginTop:spacing.md},history:{borderLeftWidth:2,borderLeftColor:colors.gold,paddingLeft:spacing.md}});
