import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import AccommodationRefundPanel from '../components/dashboard/AccommodationRefundPanel';
import { approveAccommodationRefund, completeAccommodationRefund, getAccommodationRefundableSummary, requestAccommodationRefund } from '../services/accommodationReservationService';
vi.mock('react-hot-toast', () => ({ toast: { success: vi.fn(), error: vi.fn() } }));
vi.mock('../services/accommodationReservationService', () => ({ getAccommodationRefundableSummary: vi.fn(), requestAccommodationRefund: vi.fn(), approveAccommodationRefund: vi.fn(), completeAccommodationRefund: vi.fn(), cancelAccommodationRefund: vi.fn() }));
const summary = { reservation: { total: 75000, remainingAmount: 25000 }, grossAmountPaid: 50000, refundedAmount: 10000, netAmountPaid: 40000, refundableAmount: 40000, payments: [{ _id:'P1', paymentReference:'PAY-1', allocatedAmountMinor:50000, status:'partially_refunded' }], refunds: [] };
describe('AccommodationRefundPanel', () => {
  beforeEach(() => { vi.clearAllMocks(); getAccommodationRefundableSummary.mockResolvedValue(summary); });
  test('affiche le brut, le remboursé, le net et le montant remboursable', async () => { render(<AccommodationRefundPanel reservationId="R1"/>); expect(await screen.findByText('Brut encaissé')).toBeInTheDocument(); expect(screen.getByText('Remboursé')).toBeInTheDocument(); expect(screen.getByText('Net encaissé')).toBeInTheDocument(); expect(screen.getByText('Remboursable')).toBeInTheDocument(); });
  test('refuse le dépassement puis crée une demande valide', async () => { render(<AccommodationRefundPanel reservationId="R1"/>); await screen.findByText('Brut encaissé'); fireEvent.change(screen.getByLabelText('Montant à rembourser'), { target:{ value:'50000' } }); fireEvent.change(screen.getByLabelText('Raison du remboursement'), { target:{ value:'Annulation' } }); fireEvent.click(screen.getByRole('button', { name:'Demander le remboursement' })); expect(requestAccommodationRefund).not.toHaveBeenCalled(); fireEvent.change(screen.getByLabelText('Montant à rembourser'), { target:{ value:'20000' } }); fireEvent.click(screen.getByRole('button', { name:'Demander le remboursement' })); await waitFor(() => expect(requestAccommodationRefund).toHaveBeenCalled()); });
  test('expose approbation et finalisation uniquement selon le statut', async () => { getAccommodationRefundableSummary.mockResolvedValue({ ...summary, refunds:[{ _id:'F1', amountMinor:10000, method:'cash', status:'requested', reason:'Test' }, { _id:'F2', amountMinor:5000, method:'cash', status:'approved', reason:'Test' }, { _id:'F3', amountMinor:5000, method:'cash', status:'completed', reason:'Test' }] }); vi.spyOn(window, 'confirm').mockReturnValue(true); vi.spyOn(window, 'prompt').mockReturnValueOnce('DEC-1').mockReturnValueOnce('2026-07-29'); render(<AccommodationRefundPanel reservationId="R1"/>); fireEvent.click(await screen.findByRole('button', { name:'Approuver' })); await waitFor(() => expect(approveAccommodationRefund).toHaveBeenCalled()); fireEvent.click(screen.getByRole('button', { name:'Confirmer le remboursement effectué' })); await waitFor(() => expect(completeAccommodationRefund).toHaveBeenCalled()); });
});
