import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import HotelInvoiceDeliveryPanel from '../components/HotelInvoiceDeliveryPanel';
import * as service from '../services/hotelFinancialService';
import { toast } from 'react-hot-toast';

vi.mock('react-hot-toast', () => ({ toast: { success: vi.fn(), error: vi.fn() } }));
vi.mock('../services/hotelFinancialService', () => ({ getInvoicePdfStatus: vi.fn(), listInvoiceDeliveries: vi.fn(), generateInvoicePdf: vi.fn(), downloadInvoicePdf: vi.fn(), sendInvoiceEmail: vi.fn() }));
const document = { id: 'DOC-1', status: 'issued', documentNumber: 'FAC-1', customer: { email: 'snapshot@example.test' } };

describe('HotelInvoiceDeliveryPanel F2.4', () => {
  beforeEach(() => { vi.clearAllMocks(); service.getInvoicePdfStatus.mockResolvedValue(null); service.listInvoiceDeliveries.mockResolvedValue([]); window.confirm = vi.fn(() => true); });
  test('ne propose aucun PDF officiel pour un brouillon', () => { render(<HotelInvoiceDeliveryPanel document={{ ...document, status: 'draft' }} canManage />); expect(screen.queryByText('PDF officiel')).not.toBeInTheDocument(); });
  test('génère sans double clic optimiste puis recharge l’état serveur', async () => { service.generateInvoicePdf.mockResolvedValue({ id: 'ART-1' }); service.getInvoicePdfStatus.mockResolvedValueOnce(null).mockResolvedValue({ id: 'ART-1', templateVersion: 'hotel-invoice-v1' }); render(<HotelInvoiceDeliveryPanel document={document} canManage />); const button = await screen.findByRole('button', { name: 'Générer le PDF' }); fireEvent.click(button); fireEvent.click(button); await waitFor(() => expect(service.generateInvoicePdf).toHaveBeenCalledTimes(1)); expect(await screen.findByText(/Disponible · hotel-invoice-v1/)).toBeInTheDocument(); });
  test('utilise le destinataire figé, confirme, envoie et affiche l’historique persistant', async () => { service.getInvoicePdfStatus.mockResolvedValue({ id: 'ART-1', templateVersion: 'hotel-invoice-v1' }); service.sendInvoiceEmail.mockResolvedValue({ status: 'sent' }); service.listInvoiceDeliveries.mockResolvedValueOnce([]).mockResolvedValue([{ id: 'DEL-1', requestedAt: '2026-09-03T00:00:00Z', recipient: 'snapshot@example.test', status: 'sent', artifactTemplateVersion: 'hotel-invoice-v1' }]); render(<HotelInvoiceDeliveryPanel document={document} canManage />); expect(await screen.findByDisplayValue('snapshot@example.test')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Envoyer par email' })); await waitFor(() => expect(service.sendInvoiceEmail).toHaveBeenCalledTimes(1)); expect(window.confirm).toHaveBeenCalled(); expect(await screen.findByText(/snapshot@example.test · Envoyé/)).toBeInTheDocument(); });
  test('valide le destinataire côté interface et expose l’état incertain', async () => { service.getInvoicePdfStatus.mockResolvedValue({ id: 'ART-1', templateVersion: 'hotel-invoice-v1' }); service.listInvoiceDeliveries.mockResolvedValue([{ id: 'DEL-X', requestedAt: '2026-09-03T00:00:00Z', recipient: 'snapshot@example.test', status: 'delivery_unknown', artifactTemplateVersion: 'hotel-invoice-v1' }]); render(<HotelInvoiceDeliveryPanel document={document} canManage />); fireEvent.change(await screen.findByLabelText('Destinataire'), { target: { value: 'invalide' } }); fireEvent.click(screen.getByRole('button', { name: 'Envoyer par email' })); expect(toast.error).toHaveBeenCalledWith('Adresse email invalide.'); expect(service.sendInvoiceEmail).not.toHaveBeenCalled(); expect(await screen.findByText(/Statut d’envoi incertain/)).toBeInTheDocument(); });
  test('lecture seule autorise le téléchargement mais pas génération ni envoi', async () => { service.getInvoicePdfStatus.mockResolvedValue({ id: 'ART-1', templateVersion: 'hotel-invoice-v1' }); render(<HotelInvoiceDeliveryPanel document={document} canManage={false} />); expect(await screen.findByRole('button', { name: 'Télécharger' })).toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Envoyer par email' })).not.toBeInTheDocument(); });
});
