import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { AddManagedPropertyModal } from '../pages/dashboard/GestionLocativePage';
import * as service from '../services/gestionLocativeService';

vi.mock('../services/gestionLocativeService', async () => ({
  ...(await vi.importActual('../services/gestionLocativeService')),
  getRentalOnboardingOptions: vi.fn(), onboardRentalProperty: vi.fn(),
}));

describe('Ajouter un bien à la gestion locative',()=>{
  beforeEach(()=>{ vi.clearAllMocks(); service.getRentalOnboardingOptions.mockResolvedValue({existingEligibleProperties:[{id:'p1',ownerUserId:'o1',proprietaireName:'Propriétaire Test',title:'Bien privé',address:'12 rue Test',city:'Brazzaville',type:'Appartement',price:100000}],declaredOwnerAssets:[],ineligibleProperties:[],owners:[{_id:'o1',name:'Propriétaire Test'}]}); });
  test('propose uniquement un Property existant et protège le double clic',async()=>{ service.onboardRentalProperty.mockResolvedValue({property:{_id:'p1'},rental:{_id:'r1'}}); const onSuccess=vi.fn(); render(<AddManagedPropertyModal onClose={()=>{}} onSuccess={onSuccess} toast={()=>{}}/>); await screen.findByText(/Bien privé/); expect(screen.queryByText(/Créer un nouveau bien géré/)).not.toBeInTheDocument(); fireEvent.change(screen.getAllByRole('combobox')[1],{target:{value:'p1'}}); const submit=screen.getByRole('button',{name:'Activer en gestion locative'}); fireEvent.click(submit); fireEvent.click(submit); await waitFor(()=>expect(service.onboardRentalProperty).toHaveBeenCalledTimes(1)); expect(service.onboardRentalProperty).toHaveBeenCalledWith({mode:'existing',property:'p1'}); expect(onSuccess).toHaveBeenCalled(); });
  test('filtre les Property par propriétaire et recherche métier',async()=>{ render(<AddManagedPropertyModal onClose={()=>{}} onSuccess={()=>{}} toast={()=>{}}/>); await screen.findByText(/Bien privé/); fireEvent.change(screen.getAllByRole('combobox')[0],{target:{value:'o1'}}); fireEvent.change(screen.getByLabelText('Rechercher un Property'),{target:{value:'12 rue'}}); expect(screen.getAllByRole('combobox')[1]).toHaveTextContent('Bien privé'); fireEvent.change(screen.getByLabelText('Rechercher un Property'),{target:{value:'Pointe-Noire'}}); expect(screen.getByText(/Aucun Property ne correspond/)).toBeInTheDocument(); });
  test('désactive la soumission lorsqu’aucun Property éligible n’existe',async()=>{ service.getRentalOnboardingOptions.mockResolvedValue({existingEligibleProperties:[],ineligibleProperties:[]}); render(<AddManagedPropertyModal onClose={()=>{}} onSuccess={()=>{}} toast={()=>{}}/>); expect(await screen.findByRole('button',{name:'Activer en gestion locative'})).toBeDisabled(); expect(screen.getByText(/Créez d’abord le bien depuis Immobilier/)).toBeInTheDocument(); });
  test('affiche les motifs des Property non éligibles sans proposer un import',async()=>{ service.getRentalOnboardingOptions.mockResolvedValue({existingEligibleProperties:[],ineligibleProperties:[{id:'p2',sourceType:'property',title:'Bien vendu',reason:'vendu'}]}); render(<AddManagedPropertyModal onClose={()=>{}} onSuccess={()=>{}} toast={()=>{}}/>); fireEvent.click(await screen.findByText(/Biens non éligibles/)); expect(screen.getByText(/Bien vendu — vendu/)).toBeInTheDocument(); expect(screen.queryByText(/Créer la fiche de gestion/)).not.toBeInTheDocument(); });
});
