import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { AddManagedPropertyModal } from '../pages/dashboard/GestionLocativePage';
import * as service from '../services/gestionLocativeService';

vi.mock('../services/gestionLocativeService', async () => ({
  ...(await vi.importActual('../services/gestionLocativeService')),
  getRentalOnboardingOptions: vi.fn(), onboardRentalProperty: vi.fn(), importBienIntoGestionLocative: vi.fn(),
}));

describe('Ajouter un bien à la gestion locative',()=>{
  beforeEach(()=>{ vi.clearAllMocks(); service.getRentalOnboardingOptions.mockResolvedValue({existingEligibleProperties:[{id:'p1',title:'Bien privé',city:'Brazzaville',price:100000}],declaredOwnerAssets:[],ineligibleProperties:[],owners:[{_id:'o1',name:'Propriétaire Test'}]}); });
  test('affiche les deux parcours et protège le double clic',async()=>{ service.onboardRentalProperty.mockResolvedValue({property:{_id:'p1'},rental:{_id:'r1'}}); const onSuccess=vi.fn(); render(<AddManagedPropertyModal onClose={()=>{}} onSuccess={onSuccess} toast={()=>{}}/>); await screen.findByText(/Bien privé/); fireEvent.change(screen.getByRole('combobox'),{target:{value:'p1'}}); const submit=screen.getByRole('button',{name:'Ajouter le bien'}); fireEvent.click(submit); fireEvent.click(submit); await waitFor(()=>expect(service.onboardRentalProperty).toHaveBeenCalledTimes(1)); expect(onSuccess).toHaveBeenCalled(); });
  test('valide les champs du nouveau bien',async()=>{ render(<AddManagedPropertyModal onClose={()=>{}} onSuccess={()=>{}} toast={()=>{}}/>); await screen.findByText(/Bien privé/); fireEvent.click(screen.getByRole('button',{name:/Créer un nouveau bien géré/})); fireEvent.click(screen.getByRole('button',{name:'Ajouter le bien'})); expect(service.onboardRentalProperty).not.toHaveBeenCalled(); });
  test('affiche et importe séparément un bien déclaré puis recharge les options',async()=>{ const declared={id:'b1',proprietaireId:'pr1',bienIndex:0,title:'Bien déclaré',address:'Rue 1',city:'Brazzaville',type:'Appartement',price:120000,surface:80,photos:['photo.jpg']}; service.getRentalOnboardingOptions.mockResolvedValueOnce({existingEligibleProperties:[],declaredOwnerAssets:[declared],ineligibleProperties:[],owners:[]}).mockResolvedValueOnce({existingEligibleProperties:[],declaredOwnerAssets:[],ineligibleProperties:[],owners:[]}); service.importBienIntoGestionLocative.mockResolvedValue({property:{_id:'p2'},rentalManagement:{_id:'r2'}}); const onSuccess=vi.fn(); render(<AddManagedPropertyModal onClose={()=>{}} onSuccess={onSuccess} toast={()=>{}}/>); fireEvent.click(await screen.findByRole('button',{name:'Créer la fiche de gestion'})); const textboxes=screen.getAllByRole('textbox'); fireEvent.change(textboxes[3],{target:{value:'Centre'}}); fireEvent.change(textboxes[5],{target:{value:'Description complète'}}); const numbers=screen.getAllByRole('spinbutton'); fireEvent.change(numbers[2],{target:{value:'-4.2'}}); fireEvent.change(numbers[3],{target:{value:'15.2'}}); fireEvent.click(screen.getByRole('button',{name:'Créer la fiche de gestion'})); await waitFor(()=>expect(service.importBienIntoGestionLocative).toHaveBeenCalledTimes(1)); expect(service.getRentalOnboardingOptions).toHaveBeenCalledTimes(2); expect(onSuccess).toHaveBeenCalledWith(expect.any(Object),{keepOpen:true}); });
});
