import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import TenantLinkManagement from '../components/dashboard/TenantLinkManagement';
import * as service from '../services/gestionLocativeService';

vi.mock('../services/gestionLocativeService', () => ({ getTenantLinkRequests: vi.fn(), reviewTenantLinkRequest: vi.fn(), cancelTenantInvitation: vi.fn(), resendTenantInvitation: vi.fn() }));
vi.mock('react-hot-toast', () => ({ toast: { success: vi.fn(), error: vi.fn() } }));
const invitation = { _id:'507f1f77bcf86cd799439011', type:'invitation', status:'pending', createdAt:'2026-01-01', tokenExpiresAt:'2026-01-08', locataire:{ prenom:'Jean', nom:'Test', email:'j@test.fr' } };
const request = { _id:'507f1f77bcf86cd799439012', type:'self_request', status:'pending', createdAt:'2026-01-02', locataire:{ prenom:'Anne', nom:'Test' }, user:{ name:'Anne U', email:'a@test.fr' } };
const response = (requests=[], pages=1) => ({ requests, pagination:{ page:1,pages,total:requests.length } });
describe('TenantLinkManagement', () => {
  beforeEach(()=>{ vi.clearAllMocks(); vi.spyOn(window,'confirm').mockReturnValue(true); service.getTenantLinkRequests.mockResolvedValue(response()); });
  it('affiche le chargement initial', ()=>{ service.getTenantLinkRequests.mockReturnValue(new Promise(()=>{})); render(<TenantLinkManagement/>); expect(screen.getByText(/Chargement/)).toBeInTheDocument(); });
  it('affiche la liste vide', async()=>{ render(<TenantLinkManagement/>); expect(await screen.findByText(/Aucun rattachement/)).toBeInTheDocument(); });
  it('affiche une invitation', async()=>{ service.getTenantLinkRequests.mockResolvedValue(response([invitation])); render(<TenantLinkManagement/>); expect(await screen.findByText('Jean Test')).toBeInTheDocument(); });
  it('affiche une demande et son compte', async()=>{ service.getTenantLinkRequests.mockResolvedValue(response([request])); render(<TenantLinkManagement/>); expect(await screen.findByText('Anne U')).toBeInTheDocument(); });
  it('pagine', async()=>{ service.getTenantLinkRequests.mockResolvedValue(response([invitation],2)); render(<TenantLinkManagement/>); fireEvent.click(await screen.findByText('Suivant')); await waitFor(()=>expect(service.getTenantLinkRequests).toHaveBeenLastCalledWith(expect.objectContaining({page:2}))); });
  it('filtre par statut', async()=>{ render(<TenantLinkManagement/>); fireEvent.change(screen.getByLabelText('Filtrer par statut'),{target:{value:'expired'}}); await waitFor(()=>expect(service.getTenantLinkRequests).toHaveBeenLastCalledWith(expect.objectContaining({status:'expired'}))); });
  it('recherche', async()=>{ render(<TenantLinkManagement/>); fireEvent.change(screen.getByLabelText('Rechercher un rattachement'),{target:{value:'Jean'}}); await waitFor(()=>expect(service.getTenantLinkRequests).toHaveBeenLastCalledWith(expect.objectContaining({search:'Jean'})),{timeout:1000}); });
  it('valide puis rafraîchit', async()=>{ service.getTenantLinkRequests.mockResolvedValue(response([request])); service.reviewTenantLinkRequest.mockResolvedValue({}); render(<TenantLinkManagement/>); fireEvent.click(await screen.findByText('Valider')); await waitFor(()=>expect(service.reviewTenantLinkRequest).toHaveBeenCalledWith(request._id,'approved')); expect(service.getTenantLinkRequests.mock.calls.length).toBeGreaterThan(1); });
  it('refuse après confirmation', async()=>{ service.getTenantLinkRequests.mockResolvedValue(response([request])); render(<TenantLinkManagement/>); fireEvent.click(await screen.findByText('Refuser')); await waitFor(()=>expect(service.reviewTenantLinkRequest).toHaveBeenCalledWith(request._id,'rejected')); });
  it('relance une invitation', async()=>{ service.getTenantLinkRequests.mockResolvedValue(response([invitation])); render(<TenantLinkManagement/>); fireEvent.click(await screen.findByText('Relancer')); await waitFor(()=>expect(service.resendTenantInvitation).toHaveBeenCalledWith(invitation._id)); });
  it('annule après confirmation', async()=>{ service.getTenantLinkRequests.mockResolvedValue(response([invitation])); render(<TenantLinkManagement/>); fireEvent.click(await screen.findByText('Annuler')); await waitFor(()=>expect(service.cancelTenantInvitation).toHaveBeenCalledWith(invitation._id)); });
  it.each([[401,/Session expirée/],[403,/permissions nécessaires/],[404,/Impossible de charger/],[500,/Impossible de charger/]])('présente correctement une erreur %s',async(status,message)=>{ service.getTenantLinkRequests.mockRejectedValue({response:{status}}); render(<TenantLinkManagement/>); expect(await screen.findByRole('alert')).toHaveTextContent(message); });
  it('protège contre le double clic', async()=>{ let resolve; service.getTenantLinkRequests.mockResolvedValue(response([request])); service.reviewTenantLinkRequest.mockReturnValue(new Promise(r=>{resolve=r;})); render(<TenantLinkManagement/>); const button=await screen.findByText('Valider'); fireEvent.click(button); fireEvent.click(button); expect(service.reviewTenantLinkRequest).toHaveBeenCalledTimes(1); resolve({}); });
  it('annulation refusée par confirmation ne déclenche rien', async()=>{ window.confirm.mockReturnValue(false); service.getTenantLinkRequests.mockResolvedValue(response([invitation])); render(<TenantLinkManagement/>); fireEvent.click(await screen.findByText('Annuler')); expect(service.cancelTenantInvitation).not.toHaveBeenCalled(); });
  it('affiche une erreur action sans perdre la liste', async()=>{ service.getTenantLinkRequests.mockResolvedValue(response([invitation])); service.resendTenantInvitation.mockRejectedValue({response:{data:{message:'TEST ACTION'}}}); render(<TenantLinkManagement/>); fireEvent.click(await screen.findByText('Relancer')); await waitFor(()=>expect(service.resendTenantInvitation).toHaveBeenCalled()); expect(screen.getByText('Jean Test')).toBeInTheDocument(); });
});
