"use client";
import React, { useEffect, useState } from 'react';
import { toast } from 'react-hot-toast';
import { approveAccommodationRefund, cancelAccommodationRefund, completeAccommodationRefund, getAccommodationRefundableSummary } from '../../services/accommodationReservationService';
const money = new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'XAF', maximumFractionDigits: 0 });
const operationKey = (prefix) => `${prefix}:${globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`}`;
export default function AccommodationRefundPanel({ reservationId, canManage = true, onChanged }) {
  const [summary, setSummary] = useState(null); const [busy, setBusy] = useState(false);
  const load = async () => { try { const data = await getAccommodationRefundableSummary(reservationId); setSummary(data); } catch (error) { toast.error(error.response?.data?.message || 'Résumé financier inaccessible.'); } };
  useEffect(() => { load(); }, [reservationId]); // eslint-disable-line react-hooks/exhaustive-deps
  const run = async (operation) => { if (busy) return; setBusy(true); try { await operation(); await load(); onChanged?.(); } catch (error) { toast.error(error.response?.data?.message || 'Action financière impossible.'); } finally { setBusy(false); } };
  const approve = (refund) => { if (window.confirm(`Approuver ${money.format(refund.amountMinor)} ? Cette étape ne confirme pas le décaissement.`)) run(() => approveAccommodationRefund(refund._id, operationKey('refund-approve'))); };
  const complete = (refund) => { const reference = window.prompt('Référence du décaissement réel :'); const effectiveDate = reference && window.prompt('Date effective (AAAA-MM-JJ) :', new Date().toISOString().slice(0,10)); if (reference && effectiveDate && window.confirm('Cette action confirme qu’un décaissement réel a été effectué en dehors de la plateforme.')) run(() => completeAccommodationRefund(refund._id, { reference, effectiveDate, method: 'bank_transfer', amountMinor: refund.amountMinor, comment: 'Confirmation manuelle dashboard' }, operationKey('refund-complete'))); };
  const cancel = (refund) => { const reason = window.prompt('Motif de l’annulation :'); if (reason) run(() => cancelAccommodationRefund(refund._id, reason, operationKey('refund-cancel'))); };
  if (!summary) return <p className="mt-4 text-sm">Chargement des finances…</p>;
  const amounts = [['Total', summary.reservation.total], ['Brut encaissé', summary.grossAmountPaid], ['Remboursé', summary.refundedAmount], ['Net encaissé', summary.netAmountPaid], ['Solde', summary.reservation.remainingAmount], ['Remboursable', summary.refundableAmount]];
  return <section className="mt-4 border-t pt-3" aria-label="Finances et remboursements"><h5 className="font-bold">Finances</h5><dl className="grid grid-cols-2 gap-2">{amounts.map(([label,value]) => <div key={label} className="rounded bg-slate-50 p-2"><dt className="text-xs">{label}</dt><dd className="font-semibold">{money.format(value || 0)}</dd></div>)}</dl><h6 className="mt-3 font-semibold">Paiements</h6><ul>{summary.payments.map((payment) => <li key={payment._id}>{payment.paymentReference} · {money.format(payment.allocatedAmountMinor)} · {payment.status}</li>)}</ul>
  {summary.refundableAmount > 0 && !summary.refunds.some((refund) => ['requested','approved','processing'].includes(refund.status)) && <p className="mt-3 rounded bg-amber-50 p-2 text-sm text-amber-900">Le montant est calculé par le serveur lors de l’annulation. Aucune saisie manuelle ne peut modifier cette politique.</p>}
  <h6 className="mt-3 font-semibold">Historique</h6>{summary.refunds.length ? <ul className="space-y-2">{summary.refunds.map((refund) => <li key={refund._id} className="rounded border p-2"><p><strong>{money.format(refund.amountMinor)}</strong> · {refund.method} · {refund.status}</p><p>{refund.reason}</p>{refund.manualReference && <p>Référence : {refund.manualReference}</p>}{canManage && <div className="flex gap-2">{refund.status === 'requested' && <button disabled={busy} onClick={() => approve(refund)}>Approuver</button>}{['requested','approved'].includes(refund.status) && <button disabled={busy} onClick={() => cancel(refund)}>Annuler</button>}{refund.status === 'approved' && <button disabled={busy} onClick={() => complete(refund)} className="font-semibold text-emerald-700">Confirmer le remboursement effectué</button>}</div>}</li>)}</ul> : <p>Aucun remboursement.</p>}<p className="mt-2 rounded bg-amber-50 p-2 text-xs">Un remboursement manuel atteste un décaissement réel hors plateforme. Une approbation seule ne modifie pas l’encaissement.</p></section>;
}
