import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import PageHeader from '../../components/PageHeader';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import EmptyState from '../../components/ui/EmptyState';
import Skeleton from '../../components/ui/Skeleton';
import { useTheme } from '../../context/ThemeContext';
import { fonts, fontSize, spacing } from '../../theme';
import { getPersonalDocument, openPersonalDocument } from '../../services/personalDocumentService';

const money = (value, currency = 'XAF') => value == null ? '—' : `${Number(value).toLocaleString('fr-FR')} ${currency}`;
const date = (value) => value ? new Date(value).toLocaleDateString('fr-FR') : '—';

export default function PersonalDocumentDetailScreen({ navigation, route }) {
  const { themeColors: c } = useTheme(); const styles = useMemo(() => makeStyles(c), [c]);
  const [document, setDocument] = useState(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [busy, setBusy] = useState(false); const [offline, setOffline] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async ({ refresh = false } = {}) => { if (refresh) setRefreshing(true); else setLoading(true); setError(''); try { const result = await getPersonalDocument(route.params.documentId, { refresh }); setDocument(result.document); setOffline(result.offline); if (!result.document) setError('Ce document est introuvable ou vous n’y avez plus accès.'); } catch (loadError) { setError(loadError.normalized?.message || 'Document indisponible.'); } finally { setLoading(false); setRefreshing(false); } }, [route.params.documentId]);
  useEffect(() => { load(); }, [load]);
  const open = async () => { if (offline) return Alert.alert('Connexion requise', 'Le fichier sécurisé n’est jamais conservé hors connexion.'); setBusy(true); try { await openPersonalDocument(document); } catch (openError) { Alert.alert('Ouverture impossible', openError.response?.data?.message || openError.message || 'Veuillez réessayer.'); } finally { setBusy(false); } };
  if (loading) return <SafeAreaView style={styles.safe}><PageHeader title="Document" onBack={navigation.goBack}/><View style={styles.loading}><Skeleton width="100%" height={190}/></View></SafeAreaView>;
  if (error || !document) return <SafeAreaView style={styles.safe}><PageHeader title="Document" onBack={navigation.goBack}/><EmptyState icon="lock-closed-outline" title="Document inaccessible" subtitle={error} actionLabel="Réessayer" onAction={load}/></SafeAreaView>;
  const preview = document.preview || {};
  return <SafeAreaView style={styles.safe}><PageHeader title="Document" subtitle={document.category} onBack={navigation.goBack}/><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load({ refresh: true })} tintColor={c.gold}/>}><Card style={styles.card}><Text accessibilityRole="header" style={styles.title}>{document.title}</Text><Info label="Catégorie" value={document.category} styles={styles}/><Info label="Contexte" value={document.contextLabel} styles={styles}/><Info label="Date" value={date(document.date)} styles={styles}/>{document.status && <Info label="Statut" value={document.status} styles={styles}/>} {document.paymentStatus && <Info label="Paiement" value={document.paymentStatus} styles={styles}/>} {document.amountMinor != null && <Info label="Montant" value={money(document.amountMinor, document.currency)} styles={styles}/>}</Card>{preview.lines?.length > 0 && <Card style={styles.card}><Text style={styles.subtitle}>Aperçu de la facture</Text>{preview.lines.map((line) => <View key={line.id || line.lineNumber} style={styles.line}><Text style={styles.lineText}>{line.description}</Text><Text style={styles.lineAmount}>{money(line.totalMinor, document.currency)}</Text></View>)}</Card>}<Text style={styles.security}>Le fichier est récupéré à la demande via une route authentifiée et n’est pas conservé dans le cache documentaire.</Text><Button label={offline ? 'Connexion requise' : 'Prévisualiser, télécharger ou partager'} icon="share-outline" onPress={open} loading={busy} disabled={offline || busy} fullWidth/></ScrollView></SafeAreaView>;
}
function Info({ label, value, styles }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value || '—'}</Text></View>; }
const makeStyles = (c) => StyleSheet.create({ safe: { flex: 1, backgroundColor: c.bg }, loading: { padding: spacing.md }, content: { padding: spacing.md, paddingBottom: spacing.xxl, maxWidth: 760, width: '100%', alignSelf: 'center' }, card: { marginBottom: spacing.md }, title: { color: c.text, fontFamily: fonts.display, fontSize: fontSize.xl, marginBottom: spacing.sm }, subtitle: { color: c.text, fontFamily: fonts.bodyBold, fontSize: fontSize.md, marginBottom: spacing.sm }, info: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.md, borderBottomWidth: 1, borderBottomColor: c.border, paddingVertical: spacing.sm }, label: { color: c.textSub, fontFamily: fonts.body }, value: { flex: 1, textAlign: 'right', color: c.text, fontFamily: fonts.bodyMedium }, line: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm, paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: c.border }, lineText: { flex: 1, color: c.textSub, fontFamily: fonts.body }, lineAmount: { color: c.text, fontFamily: fonts.bodyBold }, security: { color: c.textMuted, fontFamily: fonts.body, fontSize: fontSize.xs, lineHeight: 18, marginBottom: spacing.md } });
