const { sendEmailViaZoho } = require('./emailService');

const esc = (value = '') => String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const layout = (title, name, content) => `<!doctype html><html><body style="margin:0;background:#f1f5f9;font-family:Arial,sans-serif;color:#0f172a"><div style="max-width:620px;margin:32px auto;background:#fff;border-radius:16px;overflow:hidden"><div style="background:#0f3d66;color:#fff;padding:24px"><strong>ALTIMMO</strong><h1 style="font-size:22px;margin:12px 0 0">${esc(title)}</h1></div><div style="padding:28px"><p>Bonjour ${esc(name || '')},</p>${content}<p style="margin-top:28px;color:#64748b;font-size:13px">L’équipe Altimmo — Altitude Vision</p></div></div></body></html>`;
const send = (to, subject, html) => to ? sendEmailViaZoho(process.env.ZOHO_FROM_EMAIL, to, subject, html) : Promise.resolve();

exports.sendInvitation = ({ to, name, activationUrl }) => send(to, 'Invitation à votre portail locataire — Altimmo', layout('Activez votre espace locataire', name, `<p>Votre gestionnaire vous invite à accéder à votre bail, vos paiements et vos documents.</p><p><a style="display:inline-block;background:#0f6cbd;color:#fff;padding:12px 18px;border-radius:8px;text-decoration:none" href="${esc(activationUrl)}">Activer mon espace</a></p><p>Ce lien personnel expire dans 7 jours.</p>`));
exports.sendLinkDecision = ({ to, name, approved, comment }) => send(to, `Rattachement ${approved ? 'validé' : 'refusé'} — Altimmo`, layout(`Rattachement ${approved ? 'validé' : 'refusé'}`, name, `<p>Votre demande de rattachement a été <strong>${approved ? 'validée' : 'refusée'}</strong>.</p>${comment ? `<p>Message du gestionnaire : ${esc(comment)}</p>` : ''}`));
exports.sendNewDocument = ({ to, name, documentName }) => send(to, 'Nouveau document disponible — Altimmo', layout('Nouveau document', name, `<p>Le document <strong>${esc(documentName)}</strong> est disponible dans votre portail sécurisé.</p>`));
exports.sendPaymentRecorded = ({ to, name, amount, reference }) => send(to, 'Paiement enregistré — Altimmo', layout('Paiement enregistré', name, `<p>Un paiement de <strong>${esc(amount)}</strong> a été enregistré${reference ? ` sous la référence ${esc(reference)}` : ''}.</p>`));
exports.sendNoticeRecorded = ({ to, name, plannedExitAt }) => send(to, 'Préavis enregistré — Altimmo', layout('Préavis enregistré', name, `<p>Votre préavis a été enregistré. Départ prévu : <strong>${esc(plannedExitAt)}</strong>.</p>`));
