const PDFDocument = require('pdfkit');

const disclaimer = 'Ce rapport constitue un avis de valeur établi à partir des informations, documents et références disponibles à la date du calcul. Il ne remplace pas automatiquement une expertise judiciaire, notariale, bancaire ou administrative.';
const money = value => Number.isFinite(Number(value)) ? `${Number(value).toLocaleString('fr-FR')} XAF` : '—';
const date = value => value ? new Date(value).toLocaleDateString('fr-FR') : '—';

const reportData = estimation => {
  const calculation = estimation.report?.publishedCalculation || estimation.currentCalculation;
  const result = calculation?.finalResult?.marketValue || calculation?.finalResult?.marketValue === 0 ? calculation.finalResult.marketValue : null;
  return { reference: estimation.referenceBien || String(estimation._id).slice(-8).toUpperCase(), version: calculation?.version || '—', client: estimation.nom, type: estimation.typeBien, city: estimation.location?.city || estimation.adresse, calculation, result, confidence: calculation?.confidenceScore, verificationCode: estimation.report?.verificationCode, publishedAt: estimation.report?.publishedAt || estimation.publishedAt };
};
const renderHtml = estimation => { const data = reportData(estimation); return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>Rapport ${data.reference}</title><style>body{font:14px Arial;color:#1f2937;margin:32px}h1{color:#1A5A8A}h2{font-size:15px;background:#eef6ff;padding:8px}table{border-collapse:collapse;width:100%}td{padding:7px;border-bottom:1px solid #ddd}.muted{color:#6b7280}.value{font-size:20px;font-weight:bold}</style></head><body><h1>ALTITUDE VISION — ALTIMMO</h1><p class="muted">Rapport d'avis de valeur · Référence ${data.reference} · Version ${data.version}</p><h2>Bien et dossier</h2><table><tr><td>Client</td><td>${data.client || '—'}</td></tr><tr><td>Type</td><td>${data.type || '—'}</td></tr><tr><td>Ville</td><td>${data.city || '—'}</td></tr><tr><td>Date de publication</td><td>${date(data.publishedAt)}</td></tr></table><h2>Résultat validé</h2><table><tr><td>Valeur basse</td><td>${money(data.result?.low)}</td></tr><tr><td>Valeur recommandée</td><td class="value">${money(data.result?.recommended)}</td></tr><tr><td>Valeur haute</td><td>${money(data.result?.high)}</td></tr><tr><td>Confiance</td><td>${data.confidence ?? '—'}%</td></tr></table><h2>Vérification</h2><p>Code : <strong>${data.verificationCode || '—'}</strong></p><p class="muted">${disclaimer}</p></body></html>`; };
const generatePdf = estimation => new Promise((resolve, reject) => { const data = reportData(estimation); const doc = new PDFDocument({ size: 'A4', margin: 50 }); const chunks = []; doc.on('data', chunk => chunks.push(chunk)); doc.on('end', () => resolve(Buffer.concat(chunks))); doc.on('error', reject); doc.fontSize(18).fillColor('#1A5A8A').text('ALTITUDE VISION — ALTIMMO'); doc.moveDown().fillColor('#1f2937').fontSize(13).text('RAPPORT D’AVIS DE VALEUR'); doc.fontSize(10).fillColor('#6b7280').text(`Référence ${data.reference} · Version ${data.version} · ${date(data.publishedAt)}`); doc.moveDown(); [['Client', data.client], ['Type de bien', data.type], ['Ville', data.city], ['Valeur basse', money(data.result?.low)], ['Valeur recommandée', money(data.result?.recommended)], ['Valeur haute', money(data.result?.high)], ['Score de confiance', `${data.confidence ?? '—'}%`], ['Code de vérification', data.verificationCode]].forEach(([label, value]) => { doc.fillColor('#1f2937').font('Helvetica-Bold').text(`${label} : `, { continued: true }).font('Helvetica').text(value || '—'); }); doc.moveDown().fontSize(9).fillColor('#6b7280').text(disclaimer, { lineGap: 3 }); doc.end(); });
module.exports = { disclaimer, renderHtml, generatePdf };
