const asyncHandler = require('express-async-handler');
const crm = require('../services/crmService');
const scope = (req) => ({ tenantId: req.platformTenant._id, scopeUserIds: req.tenantScopeUserIds });

exports.sync = asyncHandler(async (req, res) => res.json({ status: 'success', data: { synchronization: await crm.synchronizeCustomers(req.user._id, scope(req)) } }));
exports.listCustomers = asyncHandler(async (req, res) => res.json({ status: 'success', data: await crm.listCustomers(req.query, scope(req)) }));
exports.getCustomer = asyncHandler(async (req, res) => res.json({ status: 'success', data: await crm.getCustomer360(req.params.customerId, scope(req)) }));
exports.createOpportunity = asyncHandler(async (req, res) => res.status(201).json({ status: 'success', data: { opportunity: await crm.createOpportunity(req.params.customerId, req.body, req.user._id, scope(req)) } }));
exports.moveOpportunity = asyncHandler(async (req, res) => res.json({ status: 'success', data: { opportunity: await crm.moveOpportunity(req.params.opportunityId, req.body, req.user._id, scope(req)) } }));
exports.createActivity = asyncHandler(async (req, res) => res.status(201).json({ status: 'success', data: { activity: await crm.createActivity(req.params.customerId, req.body, req.user._id, scope(req)) } }));
exports.updateActivity = asyncHandler(async (req, res) => res.json({ status: 'success', data: { activity: await crm.updateActivity(req.params.activityId, req.body, req.user._id, scope(req)) } }));
exports.dashboard = asyncHandler(async (req, res) => res.json({ status: 'success', data: await crm.getDashboard(new Date(), scope(req)) }));
exports.pipeline = asyncHandler(async (req, res) => res.json({ status: 'success', data: await crm.getPipeline(req.query, scope(req)) }));
exports.activities = asyncHandler(async (req, res) => res.json({ status: 'success', data: await crm.getActivities(req.query, new Date(), scope(req)) }));
exports.search = asyncHandler(async (req, res) => res.json({ status: 'success', data: await crm.globalSearch(req.query.q, scope(req)) }));
exports.duplicates = asyncHandler(async (req, res) => res.json({ status: 'success', data: await crm.findDuplicates(req.query, scope(req)) }));
exports.compare = asyncHandler(async (req, res) => res.json({ status: 'success', data: await crm.compareCustomers(req.params.customerA, req.params.customerB, scope(req)) }));
exports.consolidate = asyncHandler(async (req, res) => res.status(201).json({ status: 'success', data: { consolidation: await crm.consolidateCustomers(req.body, req.user._id, scope(req)) } }));
exports.consolidations = asyncHandler(async (req, res) => res.json({ status: 'success', data: { consolidations: await crm.listConsolidations(scope(req)) } }));
exports.setOpportunityOutcome = asyncHandler(async (req, res) => res.json({ status: 'success', data: { opportunity: await crm.setOpportunityOutcome(req.params.opportunityId, req.body, req.user._id, scope(req)) } }));
