const FinancialDocument = require('../models/FinancialDocument');
const FinancialDocumentLine = require('../models/FinancialDocumentLine');
const FinancialPayment = require('../models/FinancialPayment');
const PaymentAllocation = require('../models/PaymentAllocation');
const FinancialLedgerEntry = require('../models/FinancialLedgerEntry');
const HotelReservation = require('../models/HotelReservation');
const authz = require('../services/finance/financialAuthorizationService');
const { createHotelInvoiceDraftFromReservation } = require('../services/finance/hotelBillingAdapter');
const { replaceDraftLines, issueFinancialDocument } = require('../services/finance/financialDocumentService');
const { createManualPayment } = require('../services/finance/financialPaymentService');
const { allocatePaymentToDocument, reversePaymentAllocation } = require('../services/finance/paymentAllocationService');
const { fail } = require('../services/finance/financialError');

const safeDocument = (doc, lines) => ({ id: doc._id, domain: doc.domain, establishmentType: doc.establishmentType, establishmentId: doc.establishmentId, documentType: doc.documentType, documentNumber: doc.documentNumber, status: doc.status, paymentStatus: doc.paymentStatus, currency: doc.currency, subjectType: doc.subjectType, subjectId: doc.subjectId, customer: doc.customer, seller: doc.seller, issueDate: doc.issueDate, dueDate: doc.dueDate, servicePeriodStart: doc.servicePeriodStart, servicePeriodEnd: doc.servicePeriodEnd, subtotalMinor: doc.subtotalMinor, discountTotalMinor: doc.discountTotalMinor, taxTotalMinor: doc.taxTotalMinor, feesTotalMinor: doc.feesTotalMinor, totalMinor: doc.totalMinor, amountAllocatedMinor: doc.amountAllocatedMinor, balanceMinor: doc.balanceMinor, notes: doc.notes, lines });
const safePayment = (p) => ({ id: p._id, domain: p.domain, establishmentType: p.establishmentType, establishmentId: p.establishmentId, paymentReference: p.paymentReference, status: p.status, method: p.method, provider: p.provider, currency: p.currency, amountMinor: p.amountMinor, allocatedAmountMinor: p.allocatedAmountMinor, refundedAmountMinor: p.refundedAmountMinor, availableAmountMinor: p.availableAmountMinor, payer: p.payer, subjectType: p.subjectType, subjectId: p.subjectId, receivedAt: p.receivedAt, confirmedAt: p.confirmedAt });
const operationKey = (req, fallback) => String(req.headers['idempotency-key'] || req.body?.businessOperationKey || fallback);

exports.createHotelDraft = async (req, res, next) => { try { const reservation = await HotelReservation.findById(req.params.reservationId).select('hotel'); if (!reservation) fail('FINANCIAL_DOCUMENT_NOT_ISSUED', 'Réservation introuvable.', 404); await authz.assertCanCreateFinancialDraft(req.user, reservation.hotel); const document = await createHotelInvoiceDraftFromReservation({ reservationId: req.params.reservationId, actor: req.user }); const lines = await FinancialDocumentLine.find({ financialDocument: document._id }).sort('lineNumber').lean(); res.status(201).json({ status: 'success', data: { document: safeDocument(document, lines) } }); } catch (e) { next(e); } };
exports.getDocument = async (req, res, next) => { try { const doc = await FinancialDocument.findById(req.params.documentId); if (!doc) return res.status(404).json({ status: 'fail', message: 'Facture introuvable.' }); await authz.assertCanViewFinancialDocument(req.user, doc.establishmentId); const lines = await FinancialDocumentLine.find({ financialDocument: doc._id }).sort('lineNumber').lean(); res.json({ status: 'success', data: { document: safeDocument(doc, lines) } }); } catch (e) { next(e); } };
exports.updateDraft = async (req, res, next) => { try { const doc = await FinancialDocument.findById(req.params.documentId); if (!doc) fail('FINANCIAL_DOCUMENT_NOT_ISSUED', 'Facture introuvable.', 404); await authz.assertCanEditFinancialDraft(req.user, doc.establishmentId); const lines = (req.body.lines || []).map(({ description, quantity, unitAmountMinor, discountAmountMinor, taxAmountMinor, feesAmountMinor, taxes, lineType, sourceType, sourceId, serviceDate, metadata }) => ({ description, quantity, unitAmountMinor, discountAmountMinor, taxAmountMinor, feesAmountMinor, taxes, lineType, sourceType, sourceId, serviceDate, metadata })); const updated = await replaceDraftLines(doc._id, lines, req.user.id); const savedLines = await FinancialDocumentLine.find({ financialDocument: doc._id }).sort('lineNumber').lean(); res.json({ status: 'success', data: { document: safeDocument(updated, savedLines) } }); } catch (e) { next(e); } };
exports.issue = async (req, res, next) => { try { const doc = await FinancialDocument.findById(req.params.documentId); if (!doc) fail('FINANCIAL_DOCUMENT_NOT_ISSUED', 'Facture introuvable.', 404); const hotel = await authz.assertCanIssueFinancialDocument(req.user, doc.establishmentId); const issued = await issueFinancialDocument({ documentId: doc._id, actor: req.user, businessOperationKey: operationKey(req, `issue:${doc._id}`), establishmentCode: hotel._id.toString().slice(-6) }); res.json({ status: 'success', data: { document: safeDocument(issued) } }); } catch (e) { next(e); } };
exports.createManualPayment = async (req, res, next) => { try { const establishmentId = req.body.establishmentId; await authz.assertCanManageFinancialPayment(req.user, establishmentId); const payment = await createManualPayment({ data: { establishmentId, amountMinor: req.body.amountMinor, currency: req.body.currency, method: req.body.method, payer: req.body.payer, subjectType: req.body.subjectType, subjectId: req.body.subjectId, paymentReference: req.body.paymentReference, confirmed: req.body.confirmed }, actor: req.user }); res.status(201).json({ status: 'success', data: { payment: safePayment(payment) } }); } catch (e) { next(e); } };
exports.allocate = async (req, res, next) => { try { const payment = await FinancialPayment.findById(req.body.paymentId); if (!payment) fail('FINANCIAL_PAYMENT_NOT_AVAILABLE', 'Paiement introuvable.', 404); await authz.assertCanAllocatePayment(req.user, payment.establishmentId); const allocation = await allocatePaymentToDocument({ paymentId: req.body.paymentId, documentId: req.body.documentId, amountMinor: req.body.amountMinor, businessOperationKey: operationKey(req, `allocation:${req.body.paymentId}:${req.body.documentId}:${req.body.amountMinor}`), actor: req.user }); res.status(201).json({ status: 'success', data: { allocation } }); } catch (e) { next(e); } };
exports.reverseAllocation = async (req, res, next) => { try { const allocation = await PaymentAllocation.findById(req.params.allocationId); if (!allocation) fail('FINANCIAL_INVALID_TRANSITION', 'Allocation introuvable.', 404); await authz.assertCanReverseAllocation(req.user, allocation.establishmentId); const result = await reversePaymentAllocation({ allocationId: allocation._id, reason: req.body.reason, businessOperationKey: operationKey(req, `reverse:${allocation._id}`), actor: req.user }); res.json({ status: 'success', data: result }); } catch (e) { next(e); } };
exports.getLedger = async (req, res, next) => { try { const doc = await FinancialDocument.findById(req.params.documentId); if (!doc) fail('FINANCIAL_DOCUMENT_NOT_ISSUED', 'Facture introuvable.', 404); await authz.assertCanViewFinancialLedger(req.user, doc.establishmentId); const entries = await FinancialLedgerEntry.find({ establishmentId: doc.establishmentId, $or: [{ entityType: 'FinancialDocument', entityId: doc._id }, { relatedEntities: { $elemMatch: { entityType: 'FinancialDocument', entityId: doc._id } } }] }).select('-metadata').sort('occurredAt').lean(); res.json({ status: 'success', data: { entries } }); } catch (e) { next(e); } };
