const FinancialDocument = require('../models/FinancialDocument');
const FinancialDocumentLine = require('../models/FinancialDocumentLine');
const FinancialPayment = require('../models/FinancialPayment');
const PaymentAllocation = require('../models/PaymentAllocation');
const FinancialLedgerEntry = require('../models/FinancialLedgerEntry');
const HotelReservation = require('../models/HotelReservation');
const AccommodationReservation = require('../models/AccommodationReservation');
const authz = require('../services/finance/financialAuthorizationService');
const { createHotelInvoiceDraftFromReservation } = require('../services/finance/hotelBillingAdapter');
const { replaceDraftLines, issueFinancialDocument } = require('../services/finance/financialDocumentService');
const { finalizeDocumentLines } = require('../services/finance/financialDocumentService');
const { refreshHotelInvoiceDraftFromReservation } = require('../services/finance/hotelInvoiceService');
const { createManualPayment, createHotelPayment, confirmHotelPayment, rejectManualHotelPayment } = require('../services/finance/financialPaymentService');
const { uploadManualPaymentProof, readManualPaymentProof } = require('../services/finance/manualPaymentProofService');
const { generatePaymentReceipt, readPaymentReceipt } = require('../services/finance/manualPaymentReceiptService');
const { allocatePaymentToDocument, reversePaymentAllocation } = require('../services/finance/paymentAllocationService');
const { fail } = require('../services/finance/financialError');
const { generateOfficialPdf, getReadyArtifact, readAndVerifyArtifact, publicArtifact } = require('../services/finance/financialDocumentArtifactService');
const { sendOfficialInvoiceEmail, listDeliveries } = require('../services/finance/financialDocumentDeliveryService');
const { appendFinancialLedgerEntry } = require('../services/finance/financialLedgerService');
const { safeFilename } = require('../services/finance/hotelInvoicePdfRenderer');

const safeLine = (line) => ({ id: line._id, lineNumber: line.lineNumber, lineType: line.lineType, description: line.description, quantity: line.quantity, unitAmountMinor: line.unitAmountMinor, subtotalMinor: line.subtotalMinor, discountAmountMinor: line.discountAmountMinor, taxAmountMinor: line.taxAmountMinor, feesAmountMinor: line.feesAmountMinor, totalMinor: line.totalMinor, serviceDate: line.serviceDate });
const safeDocument = (doc, lines) => ({ id: doc._id, domain: doc.domain, establishmentType: doc.establishmentType, establishmentId: doc.establishmentId, documentType: doc.documentType, documentNumber: doc.documentNumber, status: doc.status, paymentStatus: doc.paymentStatus, currency: doc.currency, subjectType: doc.subjectType, subjectId: doc.subjectId, customer: doc.customer, seller: doc.seller, issueDate: doc.issueDate, dueDate: doc.dueDate, servicePeriodStart: doc.servicePeriodStart, servicePeriodEnd: doc.servicePeriodEnd, subtotalMinor: doc.subtotalMinor, discountTotalMinor: doc.discountTotalMinor, taxTotalMinor: doc.taxTotalMinor, feesTotalMinor: doc.feesTotalMinor, totalMinor: doc.totalMinor, amountAllocatedMinor: doc.amountAllocatedMinor, balanceMinor: doc.balanceMinor, notes: doc.notes, metadata: { linesFinalized: doc.metadata?.linesFinalized === true, reservationUpdatedAt: doc.metadata?.reservationUpdatedAt, sourceSnapshotHash: doc.metadata?.sourceSnapshotHash, creationSource: doc.metadata?.creationSource }, lines: lines?.map(safeLine) });
const safePayment = (p) => ({ id: p._id, domain: p.domain, establishmentType: p.establishmentType, establishmentId: p.establishmentId, paymentReference: p.paymentReference, status: p.status, method: p.method, provider: p.provider, currency: p.currency, amountMinor: p.amountMinor, allocatedAmountMinor: p.allocatedAmountMinor, refundedAmountMinor: p.refundedAmountMinor, availableAmountMinor: p.availableAmountMinor, unallocatedWarning: p.status === 'succeeded' && p.availableAmountMinor > 0 ? 'UNALLOCATED_CONFIRMED_PAYMENT' : null, payer: p.payer, subjectType: p.subjectType, subjectId: p.subjectId, receivedAt: p.receivedAt, confirmedAt: p.confirmedAt, failedAt: p.failedAt, manualValidation: p.manualValidation, proof: p.proof?.uploadedAt ? { uploadedAt: p.proof.uploadedAt, uploadedBy: p.proof.uploadedBy, downloadEndpoint: `/api/financial/payments/${p._id}/proof` } : null, createdBy: p.createdBy, confirmedBy: p.confirmedBy });
const safeAllocation = (a) => ({ id: a._id, financialPayment: a.financialPayment, financialDocument: a.financialDocument, amountMinor: a.amountMinor, currency: a.currency, status: a.status, allocatedAt: a.allocatedAt, allocatedBy: a.allocatedBy, reversedAt: a.reversedAt, reversedBy: a.reversedBy, reversalReason: a.reversalReason });
const operationKey = (req, fallback) => String(req.headers['idempotency-key'] || req.body?.businessOperationKey || fallback);
const requiredOperationKey = (req) => { const key = req.headers['idempotency-key'] || req.body?.idempotencyKey; if (!String(key || '').trim()) fail('FINANCIAL_IDEMPOTENCY_KEY_REQUIRED', 'Une clé d’idempotence est obligatoire.'); return String(key).trim(); };
const pagination = (req) => ({ page: Math.max(1, Number(req.query.page) || 1), limit: Math.min(100, Math.max(1, Number(req.query.limit) || 20)) });

const accommodationReaderRoles = ['Admin', 'Collaborateur', 'GestionnaireImmobilier', 'CommunityManager', 'Secretaire'];
async function assertAccommodationDocumentReader(user, document) {
  if (document.domain !== 'real_estate' || document.establishmentType !== 'Accommodation' || document.subjectType !== 'AccommodationReservation') return false;
  const reservation = await AccommodationReservation.findOne({ _id: document.subjectId, financialDocument: document._id }).select('guest owner');
  if (!reservation) fail('FINANCIAL_DOCUMENT_ACCESS_DENIED', 'Document de séjour inaccessible.', 403);
  const userId = String(user.id || user._id);
  if (!accommodationReaderRoles.includes(user.role) && String(reservation.guest) !== userId && String(reservation.owner) !== userId) {
    fail('FINANCIAL_DOCUMENT_ACCESS_DENIED', 'Document de séjour inaccessible.', 403);
  }
  return true;
}
async function assertHotelGuestDocumentReader(user, document) {
  if (document.domain !== 'hotel' || document.subjectType !== 'HotelReservation') return false;
  const reservation = await HotelReservation.findOne({ _id: document.subjectId, hotel: document.establishmentId }).select('guestUser');
  if (!reservation || !reservation.guestUser || String(reservation.guestUser) !== String(user.id || user._id)) return false;
  return true;
}
async function assertPersonalDocumentReader(user, document) {
  return (await assertAccommodationDocumentReader(user, document)) || (await assertHotelGuestDocumentReader(user, document));
}
async function requireDocument(req, capability, { personalRead = false } = {}) {
  const document = await FinancialDocument.findById(req.params.documentId);
  if (!document) fail('FINANCIAL_DOCUMENT_NOT_ISSUED', 'Facture introuvable.', 404);
  if (personalRead && await assertPersonalDocumentReader(req.user, document)) return document;
  await capability(req.user, document.establishmentId);
  if (document.domain !== 'hotel') fail('FINANCIAL_DOCUMENT_ACCESS_DENIED', 'Ce document ne relève pas du domaine hôtelier.', 403);
  return document;
}

exports.generateOfficialPdf = async (req, res, next) => { try {
  const document = await requireDocument(req, authz.assertCanGenerateFinancialDocumentPdf);
  const result = await generateOfficialPdf({ documentId: document._id, actor: req.user, idempotencyKey: requiredOperationKey(req) });
  res.status(result.generated ? 201 : 200).json({ status: 'success', data: result });
} catch (e) { next(e); } };

exports.getOfficialPdfStatus = async (req, res, next) => { try {
  const document = await requireDocument(req, authz.assertCanDownloadFinancialDocumentPdf, { personalRead: true });
  let artifact = null;
  try { artifact = publicArtifact(await getReadyArtifact(document._id)); } catch (error) { if (error.code !== 'FINANCIAL_PDF_NOT_AVAILABLE') throw error; }
  res.json({ status: 'success', data: { artifact } });
} catch (e) { next(e); } };

exports.downloadOfficialPdf = async (req, res, next) => { try {
  const document = await requireDocument(req, authz.assertCanDownloadFinancialDocumentPdf, { personalRead: true });
  const artifact = await getReadyArtifact(document._id); const buffer = await readAndVerifyArtifact(artifact);
  await appendFinancialLedgerEntry({ eventType: 'financial_document.pdf_downloaded', domain: document.domain, establishmentType: document.establishmentType, establishmentId: document.establishmentId, entityType: 'FinancialDocumentArtifact', entityId: artifact._id, relatedEntities: [{ entityType: 'FinancialDocument', entityId: document._id }, { entityType: document.subjectType, entityId: document.subjectId }], actorType: 'user', actorId: req.user.id || req.user._id, currency: document.currency, businessOperationKey: `artifact:${artifact._id}:download:${req.user.id || req.user._id}:${Date.now()}`, newState: { hash: artifact.hash, templateVersion: artifact.templateVersion } });
  res.set({ 'Content-Type': 'application/pdf', 'Content-Disposition': `attachment; filename="${safeFilename(document.documentNumber)}"`, 'Cache-Control': 'private, no-store, max-age=0', 'Content-Length': String(buffer.length), 'X-Content-Type-Options': 'nosniff' });
  res.send(buffer);
} catch (e) { next(e); } };

exports.sendOfficialInvoiceEmail = async (req, res, next) => { try {
  const document = await requireDocument(req, authz.assertCanSendFinancialDocumentEmail);
  const result = await sendOfficialInvoiceEmail({ documentId: document._id, actor: req.user, idempotencyKey: requiredOperationKey(req), recipient: req.body.recipient, message: req.body.message });
  res.status(result.duplicate ? 200 : 202).json({ status: 'success', data: result });
} catch (e) { next(e); } };

exports.listDocumentDeliveries = async (req, res, next) => { try {
  const document = await requireDocument(req, authz.assertCanViewFinancialDocumentDeliveries);
  res.json({ status: 'success', data: { deliveries: await listDeliveries(document._id) } });
} catch (e) { next(e); } };

exports.createHotelDraft = async (req, res, next) => { try { const reservation = await HotelReservation.findById(req.params.reservationId).select('hotel'); if (!reservation) fail('FINANCIAL_DOCUMENT_NOT_ISSUED', 'Réservation introuvable.', 404); await authz.assertCanCreateFinancialDraft(req.user, reservation.hotel); const existing = await FinancialDocument.findOne({ domain: 'hotel', subjectType: 'HotelReservation', subjectId: reservation._id }); const document = await createHotelInvoiceDraftFromReservation({ reservationId: req.params.reservationId, actor: req.user, source: 'manual' }); const lines = await FinancialDocumentLine.find({ financialDocument: document._id }).sort('lineNumber').lean(); res.status(existing ? 200 : 201).json({ status: 'success', data: { document: safeDocument(document, lines), created: !existing } }); } catch (e) { next(e); } };
exports.getDocument = async (req, res, next) => { try { const doc = await FinancialDocument.findById(req.params.documentId); if (!doc) return res.status(404).json({ status: 'fail', message: 'Facture introuvable.' }); if (!(await assertPersonalDocumentReader(req.user, doc))) await authz.assertCanViewFinancialDocument(req.user, doc.establishmentId); const lines = await FinancialDocumentLine.find({ financialDocument: doc._id }).sort('lineNumber').lean(); res.json({ status: 'success', data: { document: safeDocument(doc, lines) } }); } catch (e) { next(e); } };
exports.updateDraft = async (req, res, next) => { try { const doc = await FinancialDocument.findById(req.params.documentId); if (!doc) fail('FINANCIAL_DOCUMENT_NOT_ISSUED', 'Facture introuvable.', 404); await authz.assertCanEditFinancialDraft(req.user, doc.establishmentId); const lines = (req.body.lines || []).map(({ description, quantity, unitAmountMinor, discountAmountMinor, taxAmountMinor, feesAmountMinor, taxes, lineType, serviceDate, metadata }) => ({ description, quantity, unitAmountMinor, discountAmountMinor, taxAmountMinor, feesAmountMinor, taxes, lineType, sourceType: doc.subjectType, sourceId: doc.subjectId, serviceDate, metadata })); const updated = await replaceDraftLines(doc._id, lines, req.user.id); const savedLines = await FinancialDocumentLine.find({ financialDocument: doc._id }).sort('lineNumber').lean(); res.json({ status: 'success', data: { document: safeDocument(updated, savedLines) } }); } catch (e) { next(e); } };
exports.finalizeLines = async (req, res, next) => { try { const doc = await FinancialDocument.findById(req.params.documentId); if (!doc) fail('FINANCIAL_DOCUMENT_NOT_ISSUED', 'Facture introuvable.', 404); await authz.assertCanEditFinancialDraft(req.user, doc.establishmentId); const updated = await finalizeDocumentLines({ documentId: doc._id, actor: req.user }); const lines = await FinancialDocumentLine.find({ financialDocument: doc._id }).sort('lineNumber').lean(); res.json({ status: 'success', data: { document: safeDocument(updated, lines) } }); } catch (e) { next(e); } };
exports.refreshFromReservation = async (req, res, next) => { try { const doc = await FinancialDocument.findById(req.params.documentId); if (!doc) fail('FINANCIAL_DOCUMENT_NOT_ISSUED', 'Facture introuvable.', 404); await authz.assertCanEditFinancialDraft(req.user, doc.establishmentId); const updated = await refreshHotelInvoiceDraftFromReservation({ documentId: doc._id, actor: req.user }); const lines = await FinancialDocumentLine.find({ financialDocument: doc._id }).sort('lineNumber').lean(); res.json({ status: 'success', data: { document: safeDocument(updated, lines) } }); } catch (e) { next(e); } };
exports.getReservationDocument = async (req, res, next) => { try { const reservation = await HotelReservation.findById(req.params.reservationId).select('hotel guestUser'); if (!reservation) fail('FINANCIAL_DOCUMENT_NOT_ISSUED', 'Réservation introuvable.', 404); const isGuest = reservation.guestUser && String(reservation.guestUser) === String(req.user.id || req.user._id); if (!isGuest) await authz.assertCanViewFinancialDocument(req.user, reservation.hotel); const doc = await FinancialDocument.findOne({ domain: 'hotel', subjectType: 'HotelReservation', subjectId: reservation._id, establishmentId: reservation.hotel, documentType: 'invoice' }).sort({ createdAt: 1 }); if (!doc) return res.json({ status: 'success', data: { document: null } }); const lines = await FinancialDocumentLine.find({ financialDocument: doc._id }).sort('lineNumber').lean(); res.json({ status: 'success', data: { document: safeDocument(doc, lines) } }); } catch (e) { next(e); } };
exports.listHotelDocuments = async (req, res, next) => { try { const hotelId = req.params.hotelId; await authz.assertCanViewFinancialDocument(req.user, hotelId); const page = Math.max(1, Number(req.query.page) || 1); const limit = Math.min(100, Math.max(1, Number(req.query.limit) || 20)); const query = { domain: 'hotel', establishmentId: hotelId, documentType: 'invoice' }; if (req.query.status) query.status = req.query.status; if (req.query.reservationId) query.subjectId = req.query.reservationId; if (req.query.number) query.documentNumber = String(req.query.number); if (req.query.from || req.query.to) query.createdAt = { ...(req.query.from ? { $gte: new Date(req.query.from) } : {}), ...(req.query.to ? { $lte: new Date(req.query.to) } : {}) }; if (req.query.customer) query['customer.name'] = { $regex: String(req.query.customer).replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), $options: 'i' }; const [documents, total] = await Promise.all([FinancialDocument.find(query).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit), FinancialDocument.countDocuments(query)]); res.json({ status: 'success', data: { documents: documents.map((doc) => safeDocument(doc)), total, page, limit } }); } catch (e) { next(e); } };
// DOC-ARCH-2 — projection en lecture seule pour le Centre documentaire
// (dossier Altimmo → Hébergements → Factures), jamais une écriture ni une
// fusion de stockage avec `Document` (ADR-FIN-003/007 : FinancialDocument
// reste la source de vérité, ce endpoint ne fait que le lire). Contrairement
// à `listHotelDocuments`, aucun établissement précis n'est demandé : le
// dossier a besoin de toutes les factures d'hébergement, pas d'un seul bien
// — l'accès est donc gardé au niveau route (STAFF_IMMO), pas via
// `assertCanViewFinancialDocument` (couplé au modèle Hotel uniquement, cf.
// `assertFinancialScope`, non réutilisable tel quel pour Accommodation).
exports.listAccommodationDocuments = async (req, res, next) => { try { const page = Math.max(1, Number(req.query.page) || 1); const limit = Math.min(100, Math.max(1, Number(req.query.limit) || 20)); const query = { domain: 'real_estate', establishmentType: 'Accommodation', documentType: 'invoice' }; if (req.query.status) query.status = req.query.status; if (req.query.establishmentId) query.establishmentId = req.query.establishmentId; const [documents, total] = await Promise.all([FinancialDocument.find(query).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit), FinancialDocument.countDocuments(query)]); res.json({ status: 'success', data: { documents: documents.map((doc) => safeDocument(doc)), total, page, limit } }); } catch (e) { next(e); } };
exports.issue = async (req, res, next) => { try { const doc = await FinancialDocument.findById(req.params.documentId); if (!doc) fail('FINANCIAL_DOCUMENT_NOT_ISSUED', 'Facture introuvable.', 404); const hotel = await authz.assertCanIssueFinancialDocument(req.user, doc.establishmentId); const issued = await issueFinancialDocument({ documentId: doc._id, actor: req.user, businessOperationKey: operationKey(req, `issue:${doc._id}`), establishmentCode: hotel._id.toString().slice(-6) }); res.json({ status: 'success', data: { document: safeDocument(issued) } }); } catch (e) { next(e); } };
exports.createManualPayment = async (req, res, next) => { try { const establishmentId = req.body.establishmentId; await authz.assertCanCreateFinancialPayment(req.user, establishmentId); if (req.body.confirmed) await authz.assertCanConfirmFinancialPayment(req.user, establishmentId); const payment = await createManualPayment({ data: { establishmentId, amountMinor: req.body.amountMinor, currency: req.body.currency, method: req.body.method, payer: req.body.payer, subjectType: req.body.subjectType, subjectId: req.body.subjectId, paymentReference: req.body.paymentReference, confirmed: req.body.confirmed }, actor: req.user, businessOperationKey: requiredOperationKey(req) }); res.status(201).json({ status: 'success', data: { payment: safePayment(payment) } }); } catch (e) { next(e); } };
exports.createHotelPayment = async (req, res, next) => { try {
  const document = await FinancialDocument.findById(req.body.financialDocumentId);
  if (!document) fail('FINANCIAL_DOCUMENT_NOT_ISSUED', 'Facture introuvable.', 404);
  if (document.domain !== 'hotel' || document.status !== 'issued') fail('FINANCIAL_DOCUMENT_NOT_ISSUED', 'Une facture hôtelière émise est requise.', 409);
  if (document.currency !== 'XAF') fail('FINANCIAL_CURRENCY_UNSUPPORTED', 'Les encaissements hôteliers sont limités au XAF.', 409);
  if (String(document.subjectId) !== String(req.body.reservationId)) fail('FINANCIAL_ESTABLISHMENT_MISMATCH', 'La facture ne correspond pas à la réservation.', 409);
  const reservation = await HotelReservation.findById(req.body.reservationId).select('hotel guest guestUser');
  if (!reservation || String(reservation.hotel) !== String(document.establishmentId)) fail('FINANCIAL_ESTABLISHMENT_MISMATCH', 'Réservation, hôtel et facture incohérents.', 409);
  await authz.assertCanCreateFinancialPayment(req.user, document.establishmentId);
  if (['bank_transfer', 'card', 'mobile_money', 'cheque'].includes(req.body.method) && !String(req.body.reference || '').trim()) fail('FINANCIAL_PAYMENT_REFERENCE_REQUIRED', 'Une référence est obligatoire pour cette méthode.');
  const result = await createHotelPayment({ data: { establishmentId: document.establishmentId, documentId: document._id, reservationId: reservation._id, amountMinor: req.body.amountMinor, currency: document.currency, method: req.body.method, reference: req.body.reference, notes: req.body.notes, payer: { name: `${reservation.guest?.firstName || ''} ${reservation.guest?.lastName || ''}`.trim(), email: reservation.guest?.email, phone: reservation.guest?.phone, userId: reservation.guestUser } }, actor: req.user, businessOperationKey: requiredOperationKey(req) });
  res.status(result.created ? 201 : 200).json({ status: 'success', data: { payment: safePayment(result.payment), created: result.created } });
} catch (e) { next(e); } };
exports.confirmPayment = async (req, res, next) => { try { const payment = await FinancialPayment.findById(req.params.paymentId); if (!payment) fail('FINANCIAL_PAYMENT_NOT_AVAILABLE', 'Paiement introuvable.', 404); await authz.assertCanConfirmFinancialPayment(req.user, payment.establishmentId); const result = await confirmHotelPayment({ paymentId: payment._id, actor: req.user, businessOperationKey: requiredOperationKey(req) }); res.json({ status: 'success', data: { payment: safePayment(result.payment), confirmed: result.confirmed } }); } catch (e) { next(e); } };
exports.rejectPayment = async (req, res, next) => { try { const payment = await FinancialPayment.findById(req.params.paymentId); if (!payment) fail('FINANCIAL_PAYMENT_NOT_AVAILABLE', 'Paiement introuvable.', 404); await authz.assertCanConfirmFinancialPayment(req.user, payment.establishmentId); const result = await rejectManualHotelPayment({ paymentId: payment._id, actor: req.user, reason: req.body.reason, businessOperationKey: requiredOperationKey(req) }); res.json({ status: 'success', data: { payment: safePayment(result.payment), rejected: result.rejected } }); } catch (e) { next(e); } };
async function assertPaymentReader(user, payment) { if (payment.payer?.userId && String(payment.payer.userId) === String(user.id || user._id)) return; await authz.assertCanViewFinancialPayment(user, payment.establishmentId); }
async function assertPaymentProofWriter(user, payment) { if (payment.payer?.userId && String(payment.payer.userId) === String(user.id || user._id)) return; await authz.assertCanCreateFinancialPayment(user, payment.establishmentId); }
exports.uploadPaymentProof = async (req, res, next) => { try { const payment = await FinancialPayment.findById(req.params.paymentId); if (!payment) fail('FINANCIAL_PAYMENT_NOT_AVAILABLE', 'Paiement introuvable.', 404); await assertPaymentProofWriter(req.user, payment); const updated = await uploadManualPaymentProof({ paymentId: payment._id, actor: req.user, file: req.file }); res.status(201).json({ status: 'success', data: { payment: safePayment(updated) } }); } catch (e) { next(e); } };
exports.downloadPaymentProof = async (req, res, next) => { try { const payment = await FinancialPayment.findById(req.params.paymentId); if (!payment) fail('FINANCIAL_PAYMENT_NOT_AVAILABLE', 'Paiement introuvable.', 404); await assertPaymentReader(req.user, payment); const result = await readManualPaymentProof(payment._id); res.set({ 'Content-Type': result.asset.mimeType, 'Content-Disposition': `attachment; filename="justificatif-${payment.paymentReference}"`, 'Cache-Control': 'private, no-store, max-age=0', 'X-Content-Type-Options': 'nosniff' }); res.send(result.buffer); } catch (e) { next(e); } };
exports.generatePaymentReceipt = async (req, res, next) => { try { const payment = await FinancialPayment.findById(req.params.paymentId); if (!payment) fail('FINANCIAL_PAYMENT_NOT_AVAILABLE', 'Paiement introuvable.', 404); await authz.assertCanConfirmFinancialPayment(req.user, payment.establishmentId); const result = await generatePaymentReceipt({ paymentId: payment._id, actor: req.user }); res.status(result.generated ? 201 : 200).json({ status: 'success', data: result }); } catch (e) { next(e); } };
exports.downloadPaymentReceipt = async (req, res, next) => { try { const payment = await FinancialPayment.findById(req.params.paymentId); if (!payment) fail('FINANCIAL_PAYMENT_NOT_AVAILABLE', 'Paiement introuvable.', 404); await assertPaymentReader(req.user, payment); const result = await readPaymentReceipt(payment._id); res.set({ 'Content-Type': 'application/pdf', 'Content-Disposition': `attachment; filename="recu-${result.receipt.receiptNumber}.pdf"`, 'Cache-Control': 'private, no-store, max-age=0', 'X-Content-Type-Options': 'nosniff' }); res.send(result.buffer); } catch (e) { next(e); } };
exports.allocate = async (req, res, next) => { try { const payment = await FinancialPayment.findById(req.body.paymentId); if (!payment) fail('FINANCIAL_PAYMENT_NOT_AVAILABLE', 'Paiement introuvable.', 404); await authz.assertCanAllocatePayment(req.user, payment.establishmentId); const allocation = await allocatePaymentToDocument({ paymentId: req.body.paymentId, documentId: req.body.documentId, amountMinor: req.body.amountMinor, businessOperationKey: operationKey(req, `allocation:${req.body.paymentId}:${req.body.documentId}:${req.body.amountMinor}`), actor: req.user }); res.status(201).json({ status: 'success', data: { allocation } }); } catch (e) { next(e); } };
exports.allocateHotelPayment = async (req, res, next) => { try { const payment = await FinancialPayment.findById(req.params.paymentId); if (!payment || payment.domain !== 'hotel') fail('FINANCIAL_PAYMENT_NOT_AVAILABLE', 'Paiement hôtelier introuvable.', 404); await authz.assertCanAllocatePayment(req.user, payment.establishmentId); const allocation = await allocatePaymentToDocument({ paymentId: payment._id, documentId: req.body.documentId, amountMinor: req.body.amountMinor, businessOperationKey: requiredOperationKey(req), actor: req.user, transactionMode: 'auto' }); res.status(201).json({ status: 'success', data: { allocation: safeAllocation(allocation) } }); } catch (e) { next(e); } };
exports.reverseAllocation = async (req, res, next) => { try { const allocation = await PaymentAllocation.findById(req.params.allocationId); if (!allocation) fail('FINANCIAL_INVALID_TRANSITION', 'Allocation introuvable.', 404); await authz.assertCanReverseAllocation(req.user, allocation.establishmentId); const result = await reversePaymentAllocation({ allocationId: allocation._id, reason: req.body.reason, businessOperationKey: operationKey(req, `reverse:${allocation._id}`), actor: req.user }); res.json({ status: 'success', data: result }); } catch (e) { next(e); } };
exports.reverseHotelAllocation = async (req, res, next) => { try { const allocation = await PaymentAllocation.findById(req.params.allocationId); if (!allocation || allocation.domain !== 'hotel') fail('FINANCIAL_PAYMENT_NOT_AVAILABLE', 'Allocation hôtelière introuvable.', 404); await authz.assertCanReverseAllocation(req.user, allocation.establishmentId); const result = await reversePaymentAllocation({ allocationId: allocation._id, reason: req.body.reason, businessOperationKey: requiredOperationKey(req), actor: req.user, transactionMode: 'auto' }); const current = result.allocation || result; res.json({ status: 'success', data: { allocation: safeAllocation(current) } }); } catch (e) { next(e); } };
async function listPayments(req, res, next, base) { try { await authz.assertCanViewFinancialPayment(req.user, base.establishmentId); const { page, limit } = pagination(req); const query = { domain: 'hotel', ...base }; if (req.query.status) query.status = req.query.status; if (req.query.method) query.method = req.query.method; if (req.query.reference) query.paymentReference = { $regex: String(req.query.reference).replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), $options: 'i' }; if (req.query.from || req.query.to) query.createdAt = { ...(req.query.from ? { $gte: new Date(req.query.from) } : {}), ...(req.query.to ? { $lte: new Date(req.query.to) } : {}) }; const [payments, total] = await Promise.all([FinancialPayment.find(query).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit), FinancialPayment.countDocuments(query)]); const ids = payments.map((payment) => payment._id); const allocations = ids.length ? await PaymentAllocation.find({ financialPayment: { $in: ids } }).sort('allocatedAt').lean() : []; const byPayment = new Map(); allocations.forEach((allocation) => { const key = String(allocation.financialPayment); byPayment.set(key, [...(byPayment.get(key) || []), safeAllocation(allocation)]); }); res.json({ status: 'success', data: { payments: payments.map((payment) => ({ ...safePayment(payment), allocations: byPayment.get(String(payment._id)) || [] })), total, page, limit } }); } catch (e) { next(e); } }
exports.listHotelPayments = (req, res, next) => listPayments(req, res, next, { establishmentId: req.params.hotelId });
exports.listReservationPayments = async (req, res, next) => { const reservation = await HotelReservation.findById(req.params.reservationId).select('hotel'); if (!reservation) return next(Object.assign(new Error('Réservation introuvable.'), { code: 'FINANCIAL_PAYMENT_NOT_AVAILABLE', statusCode: 404 })); return listPayments(req, res, next, { establishmentId: reservation.hotel, subjectType: 'HotelReservation', subjectId: reservation._id }); };
exports.listDocumentPayments = async (req, res, next) => { const document = await FinancialDocument.findById(req.params.documentId); if (!document) return next(Object.assign(new Error('Facture introuvable.'), { code: 'FINANCIAL_DOCUMENT_NOT_ISSUED', statusCode: 404 })); return listPayments(req, res, next, { establishmentId: document.establishmentId, 'metadata.financialDocumentId': document._id }); };
exports.getPayment = async (req, res, next) => { try { const payment = await FinancialPayment.findById(req.params.paymentId); if (!payment || payment.domain !== 'hotel') fail('FINANCIAL_PAYMENT_NOT_AVAILABLE', 'Paiement hôtelier introuvable.', 404); await authz.assertCanViewFinancialPayment(req.user, payment.establishmentId); const allocations = await PaymentAllocation.find({ financialPayment: payment._id }).sort('allocatedAt').lean(); res.json({ status: 'success', data: { payment: { ...safePayment(payment), allocations: allocations.map(safeAllocation) } } }); } catch (e) { next(e); } };
exports.getLedger = async (req, res, next) => { try { const doc = await FinancialDocument.findById(req.params.documentId); if (!doc) fail('FINANCIAL_DOCUMENT_NOT_ISSUED', 'Facture introuvable.', 404); await authz.assertCanViewFinancialLedger(req.user, doc.establishmentId); const entries = await FinancialLedgerEntry.find({ establishmentId: doc.establishmentId, $or: [{ entityType: 'FinancialDocument', entityId: doc._id }, { relatedEntities: { $elemMatch: { entityType: 'FinancialDocument', entityId: doc._id } } }] }).select('-metadata').sort('occurredAt').lean(); res.json({ status: 'success', data: { entries } }); } catch (e) { next(e); } };
