'use client';
import { useEffect, useState } from 'react';
import { getCrmDashboard } from '../../services/crmService';

const money = (minor) => new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'XAF', maximumFractionDigits: 0 }).format((minor || 0) / 100);
const labels = { prospects:'Prospects', opportunities:'Opportunités ouvertes', activeClients:'Clients actifs', inactiveClients:'Anciens clients', revenueMinor:'Chiffre d’affaires', pendingQuotes:'Devis en attente', contractsToSign:'Contrats à signer', followupsToday:'Relances aujourd’hui', overdueTasks:'Tâches en retard', meetingsToday:'Rendez-vous du jour', newContacts:'Nouveaux contacts' };
export default function CrmDashboardPanel() {
  const [data,setData]=useState(null); const [error,setError]=useState('');
  useEffect(()=>{getCrmDashboard().then(setData).catch(e=>setError(e.response?.data?.message||'Cockpit indisponible.'));},[]);
  if(error)return <p role="alert" className="rounded-lg bg-red-50 p-4 text-red-800">{error}</p>;
  if(!data)return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:8},(_,i)=><div key={i} className="h-24 animate-pulse rounded-xl bg-slate-100"/>)}</div>;
  return <div className="space-y-6"><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6">{Object.entries(data.kpis).map(([key,value])=><article key={key} className="rounded-xl border bg-white p-4 shadow-sm"><p className="text-xs font-medium uppercase tracking-wide text-slate-500">{labels[key]}</p><p className="mt-2 text-2xl font-bold text-slate-900">{key==='revenueMinor'?money(value):value}</p></article>)}</section>
  <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Performance commerciale</h2><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-500">Taux de conversion</dt><dd className="text-xl font-bold">{data.commercial.conversionRate===null?'Non calculable':`${data.commercial.conversionRate} %`}</dd></div><div><dt className="text-slate-500">Cycle moyen</dt><dd className="text-xl font-bold">{data.commercial.averageCycleDays===null?'Non calculable':`${data.commercial.averageCycleDays} j`}</dd></div><div><dt className="text-slate-500">Gagnées</dt><dd className="text-xl font-bold text-emerald-700">{data.commercial.won}</dd></div><div><dt className="text-slate-500">Perdues</dt><dd className="text-xl font-bold text-red-700">{data.commercial.lost}</dd></div></dl><p className="mt-4 text-sm text-slate-600">Meilleur commercial : {data.commercial.bestCommercial?.name||'Non calculable'}</p></article>
  <article className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Chiffre d’affaires par pôle</h2><div className="mt-4 space-y-3">{data.commercial.revenueByPole.length?data.commercial.revenueByPole.map(x=><div key={x._id} className="flex justify-between border-b pb-2 text-sm"><span>{x._id}</span><b>{money(x.revenueMinor)}</b></div>):<p className="text-sm text-slate-500">Aucune donnée financière attribuée.</p>}</div></article></section>
  <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Activité par collaborateur</h2><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[500px] text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="p-2">Collaborateur</th><th className="p-2">Activités</th><th className="p-2">Terminées</th></tr></thead><tbody>{data.commercial.activityByCollaborator.map(x=><tr key={x.userId||'none'} className="border-b"><td className="p-2">{x.name}</td><td className="p-2">{x.total}</td><td className="p-2">{x.completed}</td></tr>)}</tbody></table></div></section></div>;
}
