import React, { useMemo, useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import * as DocumentPicker from 'expo-document-picker';
import { submitApplication, uploadApplicationAttachments } from '../../services/realEstateApplicationService';
import { colors, fonts, fontSize, spacing } from '../../theme';

export default function SubmitRealEstateApplicationScreen({ route, navigation }) {
  const { propertyId, kind = 'purchase_offer', propertyTitle = 'Bien immobilier' } = route.params;
  const rental = kind === 'rental_application'; const [amount,setAmount]=useState(''); const [moveIn,setMoveIn]=useState(''); const [duration,setDuration]=useState('12'); const [occupants,setOccupants]=useState('1'); const [income,setIncome]=useState(''); const [message,setMessage]=useState(''); const [assets,setAssets]=useState([]); const [pendingApplicationId,setPendingApplicationId]=useState(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const valid = useMemo(() => rental ? moveIn && Number(duration)>0 && Number(occupants)>0 : Number(amount)>0, [amount,duration,moveIn,occupants,rental]);
  const pick = async () => { const result=await DocumentPicker.getDocumentAsync({ type:['application/pdf','image/jpeg','image/png'], multiple:true, copyToCacheDirectory:true }); if(result.canceled)return; const next=[...assets,...result.assets].slice(0,5); const invalid=next.find((file)=>(file.size||0)>10*1024*1024); if(invalid){Alert.alert('Fichier trop volumineux','Chaque justificatif doit faire au maximum 10 Mo.');return;} setAssets(next); };
  const submit = async () => { if(!valid||busy)return; setBusy(true);setError('');try{let applicationId=pendingApplicationId;if(!applicationId){const application=await submitApplication({propertyId,validUntil:new Date(Date.now()+7*24*60*60*1000).toISOString(),message,...(rental?{desiredMoveIn:moveIn,desiredDurationMonths:Number(duration),occupants:Number(occupants),monthlyIncome:income?Number(income):undefined,incomeCurrency:'XAF'}:{amount:Number(amount),currency:'XAF'})});applicationId=application._id;setPendingApplicationId(applicationId);}if(assets.length)await uploadApplicationAttachments(applicationId,assets);navigation.replace('RealEstateApplicationDetail',{applicationId});}catch(e){setError(e.response?.data?.message||e.normalized?.message||'Envoi impossible. Vérifiez votre connexion puis réessayez. Le dossier déjà créé ne sera pas dupliqué.');}finally{setBusy(false);} };
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.body} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={styles.back}>‹ Retour</Text></TouchableOpacity><Text style={styles.title}>{rental?'Déposer une candidature':'Faire une offre'}</Text><Text style={styles.sub}>{propertyTitle}</Text>{rental?<><TextInput style={styles.input} placeholder="Date d’entrée (AAAA-MM-JJ)" value={moveIn} onChangeText={setMoveIn}/><TextInput style={styles.input} placeholder="Durée en mois" keyboardType="number-pad" value={duration} onChangeText={setDuration}/><TextInput style={styles.input} placeholder="Nombre d’occupants" keyboardType="number-pad" value={occupants} onChangeText={setOccupants}/><TextInput style={styles.input} placeholder="Revenus mensuels (facultatif)" keyboardType="number-pad" value={income} onChangeText={setIncome}/></>:<TextInput style={styles.input} placeholder="Montant proposé (XAF)" keyboardType="number-pad" value={amount} onChangeText={setAmount}/>}<TextInput style={[styles.input,styles.area]} placeholder="Message" multiline maxLength={3000} value={message} onChangeText={setMessage}/><TouchableOpacity style={styles.secondary} onPress={pick}><Text style={styles.secondaryText}>Ajouter des justificatifs ({assets.length}/5)</Text></TouchableOpacity>{assets.map((file)=><Text key={file.uri} style={styles.file} numberOfLines={1}>{file.name}</Text>)}{error?<Text accessibilityRole="alert" style={styles.error}>{error}</Text>:null}<TouchableOpacity style={[styles.primary,(!valid||busy)&&styles.disabled]} disabled={!valid||busy} onPress={submit}>{busy?<ActivityIndicator color="#fff"/>:<Text style={styles.primaryText}>Envoyer le dossier</Text>}</TouchableOpacity></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},flex:{flex:1},body:{padding:spacing.lg,gap:spacing.md},back:{color:colors.gold,fontFamily:fonts.bodyMedium},title:{fontFamily:fonts.display,fontSize:fontSize.xxl,color:colors.text},sub:{color:colors.textMuted},input:{borderWidth:1,borderColor:colors.inputBorder,borderRadius:10,padding:14,color:colors.text,backgroundColor:colors.bgCard},area:{minHeight:100,textAlignVertical:'top'},secondary:{borderWidth:1,borderColor:colors.gold,borderRadius:10,padding:14},secondaryText:{color:colors.gold,textAlign:'center',fontFamily:fonts.bodyMedium},file:{color:colors.textSub},primary:{backgroundColor:colors.blue,borderRadius:10,padding:16},primaryText:{color:'#fff',textAlign:'center',fontFamily:fonts.bodyBold},disabled:{opacity:.5},error:{color:colors.error}});
